"""GENERATED by scripts/gen_model_registry.py from config/models.registry.json — DO NOT EDIT (edit the registry, then regenerate)

Trainability partition map (FI-T3). unknown NEVER resolves to
permissive — a trace with unresolved license is reference-only."""

PROVIDER_LICENSE: dict[str, str] = {
    "baseten": "unknown",
    "cerebras": "unknown",
    "cloudflare": "unknown",
    "codestral": "unknown",
    "cohere": "unknown",
    "deepinfra": "unknown",
    "fireworks": "unknown",
    "github": "restricted",
    "googleai": "restricted",
    "groq": "unknown",
    "internai": "unknown",
    "jules": "unknown",
    "kilocode": "unknown",
    "kiro": "restricted",
    "longcat": "unknown",
    "mistral": "unknown",
    "moonshot": "unknown",
    "novita": "unknown",
    "nvidia": "unknown",
    "ollama": "permissive",
    "ollama-cloud": "unknown",
    "opencode": "unknown",
    "openmodel": "unknown",
    "openrouter": "unknown",
    "qwencloud": "unknown",
    "sambanova": "unknown",
    "scaleway": "unknown",
    "siliconflow": "unknown",
    "zai": "unknown",
    "zhipu": "unknown"
}

MODEL_LICENSE_OVERRIDES: dict[str, str] = {
    "baseten:deepseek-ai/DeepSeek-V4-Pro": "permissive",
    "baseten:moonshotai/Kimi-K2.5": "unknown",
    "baseten:moonshotai/Kimi-K2.6": "unknown",
    "baseten:moonshotai/Kimi-K2.7-Code": "unknown",
    "baseten:zai-org/GLM-4.7": "permissive",
    "baseten:zai-org/GLM-5": "permissive",
    "baseten:zai-org/GLM-5.1": "permissive",
    "baseten:zai-org/GLM-5.2": "permissive",
    "mistral:labs-leanstral-1-5-1": "permissive",
    "nvidia:deepseek-ai/deepseek-v4-flash": "permissive",
    "nvidia:deepseek-ai/deepseek-v4-pro": "permissive",
    "nvidia:minimaxai/minimax-m2.7": "restricted",
    "nvidia:minimaxai/minimax-m3": "restricted",
    "nvidia:moonshotai/kimi-k2-thinking": "unknown",
    "nvidia:moonshotai/kimi-k2.6": "unknown",
    "nvidia:qwen/qwen3-next-80b-a3b-instruct": "permissive",
    "nvidia:qwen/qwen3.5-122b-a10b": "permissive",
    "nvidia:qwen/qwen3.5-397b-a17b": "permissive",
    "nvidia:z-ai/glm-5.1": "permissive",
    "nvidia:z-ai/glm-5.2": "permissive",
    "siliconflow:MiniMaxAI/MiniMax-M2.1": "permissive",
    "siliconflow:MiniMaxAI/MiniMax-M2.5": "permissive",
    "siliconflow:MiniMaxAI/MiniMax-M3": "restricted",
    "siliconflow:Qwen/Qwen3-235B-A22B": "permissive",
    "siliconflow:Qwen/Qwen3-32B": "permissive",
    "siliconflow:deepseek-ai/DeepSeek-V4-Flash": "permissive",
    "siliconflow:deepseek-ai/DeepSeek-V4-Pro": "permissive",
    "siliconflow:moonshotai/Kimi-K2-Instruct": "unknown",
    "siliconflow:moonshotai/Kimi-K2-Thinking": "unknown",
    "siliconflow:moonshotai/Kimi-K2.6": "unknown",
    "siliconflow:zai-org/GLM-4.5": "permissive",
    "siliconflow:zai-org/GLM-5": "permissive",
    "siliconflow:zai-org/GLM-5.1": "permissive",
    "siliconflow:zai-org/GLM-5.2": "permissive"
}


def license_class(provider: str, model_id: str) -> str:
    """Effective outputLicense class for a (provider, model) pair."""
    override = MODEL_LICENSE_OVERRIDES.get(f"{provider}:{model_id}")
    if override:
        return override
    return PROVIDER_LICENSE.get(provider, "unknown")
