"""GENERATED by scripts/gen_model_registry.py from config/models.registry.json — DO NOT EDIT (edit the registry, then regenerate)"""

KNOWN_QUOTAS_GENERATED: dict = {
    "baseten": {
        "burst": None,
        "concurrent": None,
        "confidence": "HIGH",
        "credit": {
            "min_recharge_usd": None,
            "permanent_tier_rule": None,
            "trial_usd": 30.0
        },
        "degradation": "silent",
        "metering": "requests",
        "notes": "Verified-account 120 RPM/500K TPM (unverified 15/100K). SILENT-DEGRADE: 'non-enforced' budgets notify but keep charging; post-trial behavior undocumented — soak-watchlist.",
        "provider_status": "suspended",
        "tokens": {
            "monthly": None,
            "tpd": None,
            "tph": None,
            "tpm": 500000
        },
        "windows": {
            "rpd": None,
            "rph": None,
            "rpm": 120,
            "rps": None
        }
    },
    "cerebras": {
        "burst": None,
        "concurrent": None,
        "confidence": "CONFLICTED",
        "credit": {
            "min_recharge_usd": None,
            "permanent_tier_rule": None,
            "trial_usd": None
        },
        "degradation": "hard_fail",
        "metering": "requests",
        "notes": "Official 5 RPM (3 trial models) but aggregators say 30 RPM — RE-VERIFY at build. Token-bucket refill.",
        "provider_status": "suspended",
        "tokens": {
            "monthly": None,
            "tpd": 1000000,
            "tph": 1000000,
            "tpm": 30000
        },
        "windows": {
            "rpd": None,
            "rph": None,
            "rpm": 5,
            "rps": None
        }
    },
    "cloudflare": {
        "burst": None,
        "concurrent": None,
        "confidence": "HIGH",
        "credit": {
            "min_recharge_usd": None,
            "permanent_tier_rule": None,
            "trial_usd": None
        },
        "degradation": "hard_fail",
        "metering": "neurons",
        "notes": "10,000 neurons/day reset 00:00 UTC; model-specific neuron burn (70B ~204,805/M out). 100% health in god-mode report v3 (17-18 models incl Kimi K2.6, Nemotron 3 Super, GPT-OSS-120B). | legacy: 10k neurons/day; 100% health in god-mode report v3 (17-18 models incl Kimi K2.6, Nemotron 3 Super, GPT-OSS-120B)",
        "provider_status": "active",
        "tokens": {
            "monthly": None,
            "tpd": None,
            "tph": None,
            "tpm": None
        },
        "windows": {
            "rpd": None,
            "rph": None,
            "rpm": None,
            "rps": None
        }
    },
    "codestral": {
        "burst": None,
        "concurrent": None,
        "confidence": "LOW",
        "credit": {
            "min_recharge_usd": None,
            "permanent_tier_rule": None,
            "trial_usd": None
        },
        "degradation": "opaque",
        "metering": "requests",
        "notes": "",
        "provider_status": "active",
        "tokens": {
            "monthly": None,
            "tpd": None,
            "tph": None,
            "tpm": None
        },
        "windows": {
            "rpd": None,
            "rph": None,
            "rpm": None,
            "rps": None
        }
    },
    "cohere": {
        "burst": None,
        "concurrent": None,
        "confidence": "MEDIUM",
        "credit": {
            "min_recharge_usd": None,
            "permanent_tier_rule": None,
            "trial_usd": None
        },
        "degradation": "hard_fail",
        "metering": "requests",
        "notes": "1000 requests/month free tier.",
        "provider_status": "active",
        "tokens": {
            "monthly": None,
            "tpd": None,
            "tph": None,
            "tpm": None
        },
        "windows": {
            "rpd": None,
            "rph": None,
            "rpm": None,
            "rps": None
        }
    },
    "deepinfra": {
        "burst": None,
        "concurrent": None,
        "confidence": "LOW",
        "credit": {
            "min_recharge_usd": None,
            "permanent_tier_rule": None,
            "trial_usd": None
        },
        "degradation": "opaque",
        "metering": "requests",
        "notes": "",
        "provider_status": "suspended",
        "tokens": {
            "monthly": None,
            "tpd": None,
            "tph": None,
            "tpm": None
        },
        "windows": {
            "rpd": None,
            "rph": None,
            "rpm": None,
            "rps": None
        }
    },
    "fireworks": {
        "burst": None,
        "concurrent": None,
        "confidence": "LOW",
        "credit": {
            "min_recharge_usd": None,
            "permanent_tier_rule": None,
            "trial_usd": None
        },
        "degradation": "opaque",
        "metering": "requests",
        "notes": "",
        "provider_status": "suspended",
        "tokens": {
            "monthly": None,
            "tpd": None,
            "tph": None,
            "tpm": None
        },
        "windows": {
            "rpd": None,
            "rph": None,
            "rpm": None,
            "rps": None
        }
    },
    "github": {
        "burst": None,
        "concurrent": None,
        "confidence": "MEDIUM",
        "credit": {
            "min_recharge_usd": None,
            "permanent_tier_rule": None,
            "trial_usd": None
        },
        "degradation": "hard_fail",
        "metering": "requests",
        "notes": "GitHub Models free tier, 1500/day observed.",
        "provider_status": "active",
        "tokens": {
            "monthly": None,
            "tpd": 50000,
            "tph": None,
            "tpm": None
        },
        "windows": {
            "rpd": 1500,
            "rph": None,
            "rpm": None,
            "rps": None
        }
    },
    "googleai": {
        "burst": None,
        "concurrent": None,
        "confidence": "MEDIUM",
        "credit": {
            "min_recharge_usd": None,
            "permanent_tier_rule": None,
            "trial_usd": None
        },
        "degradation": "hard_fail",
        "metering": "requests",
        "notes": "Free tier 1500 req/day (KNOWN_QUOTAS-observed); Gemini 3.5 Flash free.",
        "provider_status": "active",
        "tokens": {
            "monthly": None,
            "tpd": 1000000,
            "tph": None,
            "tpm": None
        },
        "windows": {
            "rpd": 1500,
            "rph": None,
            "rpm": None,
            "rps": None
        }
    },
    "groq": {
        "burst": None,
        "concurrent": None,
        "confidence": "HIGH",
        "credit": {
            "min_recharge_usd": None,
            "permanent_tier_rule": None,
            "trial_usd": None
        },
        "degradation": "hard_fail",
        "metering": "requests",
        "notes": "Per-model org limits (8b-instant 30 RPM/6K TPM/14.4K RPD/500K TPD; 70b 30 RPM/12K TPM/1K RPD/100K TPD). Cached tokens don't count; retry-after honored. | legacy: rate-limited free tier; thermal-bath verifier role",
        "provider_status": "active",
        "tokens": {
            "monthly": None,
            "tpd": None,
            "tph": None,
            "tpm": None
        },
        "windows": {
            "rpd": None,
            "rph": None,
            "rpm": 30,
            "rps": None
        }
    },
    "internai": {
        "burst": None,
        "concurrent": 1,
        "confidence": "MEDIUM",
        "credit": {
            "min_recharge_usd": None,
            "permanent_tier_rule": None,
            "trial_usd": None
        },
        "degradation": "hard_fail",
        "metering": "tokens",
        "notes": "Operator-reported allocation 90M tokens/month (target 81M, reserve 9M); documented RPM 30, operator-conservative 20; verify reset and remaining balance before non-probe traffic. requiresVerification. | legacy: Operator-reported allocation; verify reset and remaining balance before non-probe traffic",
        "provider_status": "active",
        "tokens": {
            "monthly": 90000000,
            "tpd": None,
            "tph": None,
            "tpm": None
        },
        "windows": {
            "rpd": None,
            "rph": None,
            "rpm": 20,
            "rps": None
        }
    },
    "jules": {
        "burst": None,
        "concurrent": None,
        "confidence": "LOW",
        "credit": {
            "min_recharge_usd": None,
            "permanent_tier_rule": None,
            "trial_usd": None
        },
        "degradation": "opaque",
        "metering": "requests",
        "notes": "",
        "provider_status": "suspended",
        "tokens": {
            "monthly": None,
            "tpd": None,
            "tph": None,
            "tpm": None
        },
        "windows": {
            "rpd": None,
            "rph": None,
            "rpm": None,
            "rps": None
        }
    },
    "kilocode": {
        "burst": 4000,
        "concurrent": None,
        "confidence": "MEDIUM",
        "credit": {
            "min_recharge_usd": None,
            "permanent_tier_rule": None,
            "trial_usd": None
        },
        "degradation": "hard_fail",
        "metering": "requests",
        "notes": "Free daily-quota lane (see priorityTiers.tier_3); hourly rate limits on free models. | legacy: free daily-quota lane, see priorityTiers.tier_3",
        "provider_status": "active",
        "tokens": {
            "monthly": None,
            "tpd": None,
            "tph": None,
            "tpm": None
        },
        "windows": {
            "rpd": 500,
            "rph": 60,
            "rpm": None,
            "rps": None
        }
    },
    "kiro": {
        "burst": None,
        "concurrent": None,
        "confidence": "LOW",
        "credit": {
            "min_recharge_usd": None,
            "permanent_tier_rule": None,
            "trial_usd": None
        },
        "degradation": "opaque",
        "metering": "requests",
        "notes": "",
        "provider_status": "active",
        "tokens": {
            "monthly": None,
            "tpd": None,
            "tph": None,
            "tpm": None
        },
        "windows": {
            "rpd": None,
            "rph": None,
            "rpm": None,
            "rps": None
        }
    },
    "longcat": {
        "burst": None,
        "concurrent": 1,
        "confidence": "MEDIUM",
        "credit": {
            "min_recharge_usd": None,
            "permanent_tier_rule": None,
            "trial_usd": None
        },
        "degradation": "hard_fail",
        "metering": "tokens",
        "notes": "LongCat-2.0 partnership allocation 65M tokens (target 58.5M, reserve 6.5M); initialRpm 6, maxRpm 12; verify remaining balance and 30-day expiry before non-probe traffic. requiresVerification. | legacy: LongCat-2.0 partnership allocation; verify remaining balance and 30-day expiry before non-probe traffic",
        "provider_status": "active",
        "tokens": {
            "monthly": 65000000,
            "tpd": None,
            "tph": None,
            "tpm": None
        },
        "windows": {
            "rpd": None,
            "rph": None,
            "rpm": 6,
            "rps": None
        }
    },
    "mistral": {
        "burst": None,
        "concurrent": None,
        "confidence": "LOW",
        "credit": {
            "min_recharge_usd": None,
            "permanent_tier_rule": None,
            "trial_usd": None
        },
        "degradation": "opaque",
        "metering": "requests",
        "notes": "",
        "provider_status": "active",
        "tokens": {
            "monthly": None,
            "tpd": None,
            "tph": None,
            "tpm": None
        },
        "windows": {
            "rpd": None,
            "rph": None,
            "rpm": None,
            "rps": None
        }
    },
    "moonshot": {
        "burst": None,
        "concurrent": 1,
        "confidence": "HIGH",
        "credit": {
            "min_recharge_usd": 1.0,
            "permanent_tier_rule": None,
            "trial_usd": None
        },
        "degradation": "dynamic_throttle",
        "metering": "requests",
        "notes": "NO $0 API tier — $1 min recharge (aggregator '1000 free req/day' is the chat app, not API). Tier 0 after recharge. Dynamic under-load throttling.",
        "provider_status": "suspended",
        "tokens": {
            "monthly": None,
            "tpd": 1500000,
            "tph": None,
            "tpm": 500000
        },
        "windows": {
            "rpd": None,
            "rph": None,
            "rpm": 3,
            "rps": None
        }
    },
    "novita": {
        "burst": None,
        "concurrent": None,
        "confidence": "LOW",
        "credit": {
            "min_recharge_usd": None,
            "permanent_tier_rule": None,
            "trial_usd": 0.5
        },
        "degradation": "hard_fail",
        "metering": "requests",
        "notes": "$0.50 one-time trial credit; ~60 RPM unverified.",
        "provider_status": "suspended",
        "tokens": {
            "monthly": None,
            "tpd": None,
            "tph": None,
            "tpm": None
        },
        "windows": {
            "rpd": None,
            "rph": None,
            "rpm": 60,
            "rps": None
        }
    },
    "nvidia": {
        "burst": None,
        "concurrent": 1,
        "confidence": "MEDIUM",
        "credit": {
            "min_recharge_usd": None,
            "permanent_tier_rule": None,
            "trial_usd": None
        },
        "degradation": "silent",
        "metering": "requests",
        "notes": "Operator-conservative 8 RPM (community reports ~40 free / ~200 on request; NO official page). noParallelSubagents. 429/burst undocumented — soak-watchlist.",
        "provider_status": "active",
        "tokens": {
            "monthly": None,
            "tpd": None,
            "tph": None,
            "tpm": None
        },
        "windows": {
            "rpd": None,
            "rph": None,
            "rpm": 8,
            "rps": None
        }
    },
    "ollama": {
        "burst": None,
        "concurrent": None,
        "confidence": "LOW",
        "credit": {
            "min_recharge_usd": None,
            "permanent_tier_rule": None,
            "trial_usd": None
        },
        "degradation": "opaque",
        "metering": "requests",
        "notes": "",
        "provider_status": "active",
        "tokens": {
            "monthly": None,
            "tpd": None,
            "tph": None,
            "tpm": None
        },
        "windows": {
            "rpd": None,
            "rph": None,
            "rpm": None,
            "rps": None
        }
    },
    "ollama-cloud": {
        "burst": None,
        "concurrent": None,
        "confidence": "MEDIUM",
        "credit": {
            "min_recharge_usd": None,
            "permanent_tier_rule": None,
            "trial_usd": None
        },
        "degradation": "opaque",
        "metering": "gpu_time",
        "notes": "Free/Pro $20/Max $100; GPU-time weight classes L1-L4; 5h session + weekly resets; opaque metering, no numeric caps published — soak-watchlist.",
        "provider_status": "active",
        "tokens": {
            "monthly": None,
            "tpd": None,
            "tph": None,
            "tpm": None
        },
        "windows": {
            "rpd": None,
            "rph": None,
            "rpm": None,
            "rps": None
        }
    },
    "opencode": {
        "burst": 8000,
        "concurrent": None,
        "confidence": "MEDIUM",
        "credit": {
            "min_recharge_usd": None,
            "permanent_tier_rule": None,
            "trial_usd": None
        },
        "degradation": "hard_fail",
        "metering": "requests",
        "notes": "Free daily-quota lane (see priorityTiers.tier_3); burst = tokens/call observed. | legacy: free daily-quota lane, see priorityTiers.tier_3",
        "provider_status": "active",
        "tokens": {
            "monthly": None,
            "tpd": 50000,
            "tph": None,
            "tpm": None
        },
        "windows": {
            "rpd": 200,
            "rph": None,
            "rpm": None,
            "rps": None
        }
    },
    "openmodel": {
        "burst": None,
        "concurrent": None,
        "confidence": "LOW",
        "credit": {
            "min_recharge_usd": None,
            "permanent_tier_rule": None,
            "trial_usd": None
        },
        "degradation": "opaque",
        "metering": "requests",
        "notes": "",
        "provider_status": "pending_operator",
        "tokens": {
            "monthly": None,
            "tpd": None,
            "tph": None,
            "tpm": None
        },
        "windows": {
            "rpd": None,
            "rph": None,
            "rpm": None,
            "rps": None
        }
    },
    "openrouter": {
        "burst": None,
        "concurrent": None,
        "confidence": "HIGH",
        "credit": {
            "min_recharge_usd": None,
            "permanent_tier_rule": "rpd 50 -> 1000 permanently once >= $10 credits ever bought",
            "trial_usd": None
        },
        "degradation": "hard_fail",
        "metering": "requests",
        "notes": ":free models; negative balance -> 402 even on free models; Cloudflare DDoS layer blocks independently. /models polling needs NO credits.",
        "provider_status": "active",
        "tokens": {
            "monthly": None,
            "tpd": None,
            "tph": None,
            "tpm": None
        },
        "windows": {
            "rpd": 50,
            "rph": None,
            "rpm": 20,
            "rps": None
        }
    },
    "qwencloud": {
        "burst": None,
        "concurrent": None,
        "confidence": "HIGH",
        "credit": {
            "min_recharge_usd": None,
            "permanent_tier_rule": None,
            "trial_usd": None
        },
        "degradation": "hard_fail",
        "metering": "tokens",
        "notes": "1M free tokens PER eligible model, 90 days from Model Studio activation; hard stop AllocationQuota.FreeTierOnly; free quota only SG/FRA/HK regions, NOT us-virginia (MEDIUM). | legacy: 1M free tokens PER eligible model, Singapore intl endpoint, 90 days from Model Studio activation (web-verified 2026-07)",
        "provider_status": "pending_operator",
        "tokens": {
            "monthly": 1000000,
            "tpd": None,
            "tph": None,
            "tpm": None
        },
        "windows": {
            "rpd": None,
            "rph": None,
            "rpm": None,
            "rps": None
        }
    },
    "sambanova": {
        "burst": None,
        "concurrent": None,
        "confidence": "LOW",
        "credit": {
            "min_recharge_usd": None,
            "permanent_tier_rule": None,
            "trial_usd": None
        },
        "degradation": "opaque",
        "metering": "requests",
        "notes": "",
        "provider_status": "suspended",
        "tokens": {
            "monthly": None,
            "tpd": None,
            "tph": None,
            "tpm": None
        },
        "windows": {
            "rpd": None,
            "rph": None,
            "rpm": None,
            "rps": None
        }
    },
    "scaleway": {
        "burst": None,
        "concurrent": None,
        "confidence": "MEDIUM",
        "credit": {
            "min_recharge_usd": None,
            "permanent_tier_rule": None,
            "trial_usd": None
        },
        "degradation": "hard_fail",
        "metering": "tokens",
        "notes": "1M free tokens, largely unspent.",
        "provider_status": "active",
        "tokens": {
            "monthly": 1000000,
            "tpd": None,
            "tph": None,
            "tpm": None
        },
        "windows": {
            "rpd": None,
            "rph": None,
            "rpm": None,
            "rps": None
        }
    },
    "siliconflow": {
        "burst": None,
        "concurrent": None,
        "confidence": "HIGH",
        "credit": {
            "min_recharge_usd": None,
            "permanent_tier_rule": None,
            "trial_usd": None
        },
        "degradation": "hard_fail",
        "metering": "requests",
        "notes": "Free models $0; L0-L5 tiers by monthly consumption. '50/day->1000/day after CNY10' secondary-sourced.",
        "provider_status": "active",
        "tokens": {
            "monthly": None,
            "tpd": None,
            "tph": None,
            "tpm": None
        },
        "windows": {
            "rpd": None,
            "rph": None,
            "rpm": None,
            "rps": None
        }
    },
    "zai": {
        "burst": None,
        "concurrent": None,
        "confidence": "LOW",
        "credit": {
            "min_recharge_usd": None,
            "permanent_tier_rule": None,
            "trial_usd": None
        },
        "degradation": "opaque",
        "metering": "requests",
        "notes": "",
        "provider_status": "deprecated",
        "tokens": {
            "monthly": None,
            "tpd": None,
            "tph": None,
            "tpm": None
        },
        "windows": {
            "rpd": None,
            "rph": None,
            "rpm": None,
            "rps": None
        }
    },
    "zhipu": {
        "burst": None,
        "concurrent": 1,
        "confidence": "LOW",
        "credit": {
            "min_recharge_usd": None,
            "permanent_tier_rule": None,
            "trial_usd": None
        },
        "degradation": "hard_fail",
        "metering": "requests",
        "notes": "~1000 req/day free, Flash models fully free. MOST VOLATILE (free limits changed 2x in 12mo); registration may need CN phone.",
        "provider_status": "suspended",
        "tokens": {
            "monthly": None,
            "tpd": None,
            "tph": None,
            "tpm": None
        },
        "windows": {
            "rpd": 1000,
            "rph": None,
            "rpm": None,
            "rps": None
        }
    }
}

PROVIDER_QUIRKS_GENERATED: dict = {
    "baseten": [
        {
            "action": "soak_watchlist",
            "appliesTo": [
                "*"
            ],
            "confidence": "HIGH",
            "id": "baseten-nonenforced-budget",
            "kind": "silent_degradation",
            "notes": "'Non-enforced' budgets notify but keep charging; post-trial behavior undocumented"
        },
        {
            "action": "monitor_credit_floor",
            "appliesTo": [
                "*"
            ],
            "confidence": "MEDIUM",
            "id": "dollar-then-dead",
            "kind": "dollar_then_dead",
            "notes": "Degradation class: provider serves normally until residual trial credit ~$1, then quality/availability collapses without error"
        }
    ],
    "cloudflare": [
        {
            "action": "alias_check_before_removal",
            "appliesTo": [
                "*"
            ],
            "confidence": "HIGH",
            "id": "cf-auto-alias-renames",
            "kind": "silent_rename",
            "notes": "Auto-aliased kimi-k2.5 -> k2.6 on 2026-05-30 — a removed listing row may be a rename, not a removal"
        }
    ],
    "moonshot": [
        {
            "action": "require_recharge_before_routing",
            "appliesTo": [
                "*"
            ],
            "confidence": "HIGH",
            "id": "moonshot-no-free-tier",
            "kind": "no_free_tier",
            "notes": "$1 minimum recharge; the widely-repeated '1000 free req/day' is the chat app, NOT the API"
        },
        {
            "action": "soak_watchlist",
            "appliesTo": [
                "*"
            ],
            "confidence": "HIGH",
            "id": "moonshot-underload-throttle",
            "kind": "dynamic_throttle",
            "notes": "Dynamic under-load throttling on Tier 0"
        }
    ],
    "nvidia": [
        {
            "action": "route_tools_elsewhere",
            "appliesTo": [
                "moonshotai/kimi-2.6*"
            ],
            "confidence": "HIGH",
            "id": "kimi26-nim-tool-calls",
            "kind": "tool_calling_broken",
            "notes": "Kimi-2.6 on NIM emits malformed/absent tool calls (lane-observed 2026-06); route tool-calling work to other providers"
        },
        {
            "action": "soak_watchlist",
            "appliesTo": [
                "*"
            ],
            "confidence": "MEDIUM",
            "id": "nim-silent-degrade",
            "kind": "silent_degradation",
            "notes": "429/burst behavior undocumented; community-sourced limits only"
        },
        {
            "action": "timeout_and_rotate",
            "appliesTo": [
                "minimaxai/minimax-m3"
            ],
            "confidence": "MEDIUM",
            "id": "minimax-m3-nim-hang",
            "kind": "intermittent_hang",
            "notes": "MiniMax-M3 on NIM hangs intermittently mid-stream (lane-observed 2026-07-05/06, blocked the opencode NEXUS-BENCH session); use aggressive read timeouts"
        }
    ],
    "ollama-cloud": [
        {
            "action": "soak_watchlist",
            "appliesTo": [
                "*"
            ],
            "confidence": "MEDIUM",
            "id": "ollama-cloud-opaque-metering",
            "kind": "silent_degradation",
            "notes": "GPU-time weight classes with no published numeric caps; 5h session + weekly resets"
        }
    ]
}
