"""Generate routing tables from config/models.registry.json (single source of truth).

Emits four checked-in artifacts (deterministic — no timestamps — so a
byte-equality drift test can prove the registry and its consumers agree):

1. src/lib/modelrelay/config.generated.ts   — Node relay PROVIDERS/MODELS
2. nexus_os/relay/quota_limits_generated.py — context-window clamp table
3. nexus_os/twave/cloud_profiles_generated.json — Chimera cloud-tier profiles
4. nexus_os/relay/ollama_map_generated.py   — local/cloud Ollama model map
5. nexus_os/gmr/domain_mapping_generated.py — GMR domain routing tables
6. nexus_os/model_relay/known_quotas_generated.py — structured v3 quota feed
7. nexus_os/relay/tracing/license_map_generated.py — outputLicense partition map
8. nexus_os/relay/scores_generated.py — evidence-backed benchmark dimensions

Artifacts 3, 5 and 8 additionally read config/arena_scores.snapshot.json —
a committed lockfile-style arena snapshot (seeded from nexus_os.relay.arena_ingest
data; absent file tolerated) — so generation stays deterministic.

Usage:
    python scripts/gen_model_registry.py [--check] [--only chimera,domains,scores]
        --check: exit 1 on drift
        --only:  restrict to a comma-separated artifact subset
                 (ts, quota, chimera, ollama, domains, known_quotas, license, scores)
"""
from __future__ import annotations

import argparse
import difflib
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
REGISTRY = REPO / "config" / "models.registry.json"

TS_OUT = REPO / "src" / "lib" / "modelrelay" / "config.generated.ts"
QUOTA_OUT = REPO / "nexus_os" / "relay" / "quota_limits_generated.py"
CHIMERA_OUT = REPO / "nexus_os" / "twave" / "cloud_profiles_generated.json"
OLLAMA_OUT = REPO / "nexus_os" / "relay" / "ollama_map_generated.py"
DOMAINS_OUT = REPO / "nexus_os" / "gmr" / "domain_mapping_generated.py"
QUOTAS_OUT = REPO / "nexus_os" / "model_relay" / "known_quotas_generated.py"
LICENSE_OUT = REPO / "nexus_os" / "relay" / "tracing" / "license_map_generated.py"
SCORES_OUT = REPO / "nexus_os" / "relay" / "scores_generated.py"
ARENA_SNAPSHOT = REPO / "config" / "arena_scores.snapshot.json"

BENCHMARK_FIELDS = (
    ("quality", "arena_score"),
    ("code", "code_score"),
    ("reasoning", "reasoning_score"),
    ("swe", "swe_score"),
    ("speed", "speed_score"),
    ("cost_efficiency", "cost_efficiency_score"),
)

#: GMR domain -> registry roles eligible for that domain's primary list.
DOMAIN_ROLES = {
    "code": ("code",),
    "reasoning": ("reasoning",),
    "research": ("frontier",),
    "fast": ("fast",),
    "security": ("judge", "guard"),
    "general": ("frontier",),
}

HEADER = "GENERATED by scripts/gen_model_registry.py from config/models.registry.json — DO NOT EDIT (edit the registry, then regenerate)"

LOCAL_PROVIDERS = {"ollama"}


def _env_key(slug: str) -> str:
    return slug.upper().replace("-", "_") + "_API_KEY"


def _quota_rpm(prov: dict):
    """RPM from a v3 structured quota block (flat v2 fallback kept)."""
    quota = prov.get("quota") or {}
    windows = quota.get("windows")
    if isinstance(windows, dict):
        return windows.get("rpm")
    return quota.get("rpm")


def _load_arena(path: Path = ARENA_SNAPSHOT) -> dict:
    """{registry_id: snapshot entry} from the committed arena snapshot.

    Tolerates an absent/unreadable file (empty dict -> every model falls
    back to explicit unscored values downstream). A fixture-seeded snapshot
    is tagged here so its self-reported confidence cannot be promoted to
    high-confidence runtime evidence.
    """
    try:
        data = json.loads(Path(path).read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    models = data.get("models") if isinstance(data, dict) else None
    if not isinstance(models, dict):
        return {}
    note = str(data.get("note") or "").lower()
    evidence_kind = "fixture" if "fixture" in note else "benchmark_snapshot"
    loaded = {}
    for registry_id, raw_entry in models.items():
        if not isinstance(raw_entry, dict):
            continue
        entry = dict(raw_entry)
        confidence = str(entry.get("confidence") or "unknown").lower()
        if evidence_kind == "fixture" and confidence == "high":
            confidence = "low"
        entry["_evidence_kind"] = evidence_kind
        entry["_confidence"] = confidence
        loaded[registry_id] = entry
    return loaded


def _bounded_score(value):
    if not isinstance(value, (int, float)):
        return None
    return round(min(max(float(value), 0.0), 1.0), 4)


def _benchmark_record(model: dict, arena: dict) -> tuple[dict, dict]:
    """Return independent benchmark dimensions plus explicit provenance.

    Registry tier is retained only under policy_prior. It never fills a
    missing benchmark category and is never blended into benchmark evidence.
    """
    raw_entry = arena.get(model["id"])
    entry = raw_entry if isinstance(raw_entry, dict) else None
    sources = entry.get("sources") if entry else None
    source_list = list(sources) if isinstance(sources, list) else []
    dimensions = {
        dimension: _bounded_score(entry.get(source_key)) if entry else None
        for dimension, source_key in BENCHMARK_FIELDS
    }
    has_evidence = bool(source_list) and any(
        value is not None for value in dimensions.values()
    )
    policy_prior = {"registry_tier": model.get("tier")}
    if not has_evidence:
        return ({dimension: None for dimension, _ in BENCHMARK_FIELDS}, {
            "provenance": "unscored",
            "weights": {},
            "components": {},
            "policy_prior": policy_prior,
            "as_of": None,
            "sources": [],
            "evidence_kind": "none",
            "confidence": "none",
        })

    components = {
        source_key: entry.get(source_key)
        for _dimension, source_key in BENCHMARK_FIELDS
        if isinstance(entry.get(source_key), (int, float))
    }
    return dimensions, {
        "provenance": "benchmark_snapshot",
        "weights": {},
        "components": components,
        "policy_prior": policy_prior,
        "as_of": entry.get("as_of"),
        "sources": source_list,
        "evidence_kind": entry.get("_evidence_kind", "benchmark_snapshot"),
        "confidence": entry.get(
            "_confidence", str(entry.get("confidence") or "unknown").lower()
        ),
    }


def _evidence_rank(dimensions: dict) -> tuple:
    ordered = [dimensions.get(name) for name, _source in BENCHMARK_FIELDS]
    present = sum(value is not None for value in ordered)
    return (present, *(value if value is not None else -1.0 for value in ordered))


def _ts_provider(slug: str, prov: dict) -> dict:
    rpm = _quota_rpm(prov)
    return {
        "id": slug,
        "name": slug,
        "provider": slug,
        "baseUrl": prov["baseUrl"].rstrip("/"),
        "chatPath": prov.get("chatPath", "/chat/completions"),
        "modelsPath": prov.get("modelsPath", "/models"),
        "authType": "x-api-key" if prov.get("authHeader", "").lower() == "x-goog-api-key" else ("none" if prov.get("keyRef") is None else "bearer"),
        "quotaType": "free_tier",
        "quotaRemaining": rpm if isinstance(rpm, int) else "varies",
        "costPer1m": 0.0,
        "latencyMs": 400,
        "status": "up" if prov["status"] == "active" else "down",
        "tier": 50,
        "priority": prov.get("priority", 50),
        "isFree": True,
        "isLocal": slug in LOCAL_PROVIDERS,
        "models": [],
        "envKey": _env_key(slug),
        "keyRef": prov.get("keyRef"),
    }


def _ts_model(m: dict) -> dict:
    caps = m.get("capabilities") or {}
    active = m["status"] == "active"
    return {
        "modelId": f"{m['provider']}/{m['id']}",
        "provider": m["provider"],
        "name": m["id"],
        "tier": m.get("tier") or 50,
        "costPer1mInput": 0,
        "costPer1mOutput": 0,
        "contextWindow": m.get("context") or 32768,
        "latencyMsTypical": 500,
        "supportsVision": bool(caps.get("vision")),
        "supportsFunctionCalling": bool(caps.get("tools")),
        "supportsStreaming": True,
        "isFree": m.get("free") is not False,
        "isLocal": m["provider"] in LOCAL_PROVIDERS,
        "status": "up" if active else "down",
    }


def emit_ts(registry: dict) -> str:
    providers = {}
    for slug in sorted(registry["providers"]):
        prov = registry["providers"][slug]
        if not prov.get("baseUrl"):
            continue  # discovery-only providers stay on the npm relay / legacy config
        if prov["status"] == "deprecated":
            continue
        providers[slug] = _ts_provider(slug, prov)

    prov_status = {k: v["status"] for k, v in registry["providers"].items()}
    models = []
    for m in sorted(registry["models"], key=lambda x: (x["provider"], x["id"])):
        if m["provider"] not in providers:
            continue
        entry = _ts_model(m)
        if prov_status.get(m["provider"]) != "active":
            entry["status"] = "down"
        models.append(entry)
        providers[m["provider"]]["models"].append(m["id"])

    deprecated = sorted(
        slug for slug, p in registry["providers"].items() if p["status"] == "deprecated"
    )

    lines = [
        "/**",
        f" * {HEADER}",
        " */",
        "import type { ProviderConfig, ModelInfo } from './config'",
        "",
        "export const REGISTRY_VERSION = %d" % registry["version"],
        "",
        "// Providers the registry retired — the merge facade must drop their",
        "// legacy config.ts entries (e.g. the dead keyless zai/glm-5.2 block).",
        "export const DEPRECATED_PROVIDERS: string[] = " + json.dumps(deprecated),
        "",
        "export const PROVIDERS_GENERATED: Record<string, ProviderConfig & { keyRef?: string | null }> = "
        + json.dumps(providers, indent=2, ensure_ascii=False),
        "",
        "export const MODELS_GENERATED: ModelInfo[] = "
        + json.dumps(models, indent=2, ensure_ascii=False),
        "",
    ]
    return "\n".join(lines)


def emit_quota(registry: dict) -> str:
    limits: dict[str, int] = {}
    for m in registry["models"]:
        ctx = m.get("context")
        if not ctx:
            continue
        for key in (m["id"], *m.get("aliases", [])):
            existing = limits.get(key)
            # Conservative on collision: the SMALLEST window wins so the
            # clamp can never overshoot the real provider limit.
            limits[key] = min(existing, ctx) if existing else ctx
    body = json.dumps(dict(sorted(limits.items())), indent=4, ensure_ascii=False)
    # JSON -> Python literal (true/false/null never appear in this int map)
    return (
        f'"""{HEADER}"""\n\n'
        f"KNOWN_CONTEXT_LIMITS: dict[str, int] = {body}\n"
    )


def emit_chimera(registry: dict, arena: dict) -> str:
    prov_status = {k: v["status"] for k, v in registry["providers"].items()}
    profiles = []
    seen = set()
    for m in sorted(registry["models"], key=lambda x: -(x.get("tier") or 0)):
        if m["status"] != "active" or prov_status.get(m["provider"]) != "active":
            continue
        if m["provider"] in LOCAL_PROVIDERS:
            continue  # local hardware profiles stay hand-authored in chimera
        if "frontier" not in m.get("roles", []) and "reasoning" not in m.get("roles", []) and "code" not in m.get("roles", []):
            continue
        if m["id"] in seen:
            continue
        seen.add(m["id"])
        caps = m.get("capabilities") or {}
        benchmark_scores, benchmark_provenance = _benchmark_record(m, arena)
        registry_tier = m.get("tier") or 50
        profiles.append({
            "name": m["id"],
            "provider": m["provider"],
            # Compatibility routing estimate. It is a policy prior, not a bench.
            "quality_score": round(registry_tier / 100.0, 2),
            "quality_provenance": "policy_prior.registry_tier",
            "policy_prior": {"registry_tier": registry_tier},
            "benchmark_scores": benchmark_scores,
            "benchmark_provenance": benchmark_provenance,
            "max_context": m.get("context") or 32768,
            "supports_thinking": bool(caps.get("thinking")),
            "roles": m.get("roles", []),
        })
    payload = {
        "_comment": HEADER,
        "_quality_contract": (
            "quality_score is an operational registry-tier prior; "
            "benchmark_scores are independent evidenced dimensions or null"
        ),
        "cloud_profiles": profiles,
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def emit_ollama(registry: dict) -> str:
    mapping: dict[str, str] = {}
    cloud: list[str] = []
    prov_status = {k: v["status"] for k, v in registry["providers"].items()}
    for m in registry["models"]:
        if m["provider"] == "ollama":
            for alias in m.get("aliases", []):
                mapping[alias] = m["id"]
            mapping[m["id"]] = m["id"]
        elif m["provider"] == "ollama-cloud":
            cloud.append(m["id"])
            for alias in m.get("aliases", []):
                mapping[alias] = m["id"]
    
    # Also collect all active cloud models from all active providers
    active_cloud_models: list[str] = []
    for m in registry["models"]:
        if m["status"] == "active" and prov_status.get(m["provider"]) == "active":
            if m["provider"] != "ollama":
                # Add short ID
                active_cloud_models.append(m["id"])
                # Add provider prefixed ID
                active_cloud_models.append(f"{m['provider']}/{m['id']}")
                # Add aliases
                for alias in m.get("aliases", []):
                    active_cloud_models.append(alias)
                    active_cloud_models.append(f"{m['provider']}/{alias}")
                    
    # Deduplicate and sort
    active_cloud_models = sorted(list(set(active_cloud_models)))

    return (
        f'"""{HEADER}"""\n\n'
        f"OLLAMA_MODEL_MAP: dict[str, str] = {json.dumps(dict(sorted(mapping.items())), indent=4, ensure_ascii=False)}\n\n"
        f"OLLAMA_CLOUD_MODELS: list[str] = {json.dumps(sorted(set(cloud)), indent=4, ensure_ascii=False)}\n\n"
        f"ALL_ACTIVE_CLOUD_MODELS: list[str] = {json.dumps(active_cloud_models, indent=4, ensure_ascii=False)}\n"
    )



def emit_domains(registry: dict, arena: dict) -> str:
    prov_status = {k: v["status"] for k, v in registry["providers"].items()}
    domains: dict = {}
    for domain, roles in DOMAIN_ROLES.items():
        entries = []
        for m in registry["models"]:
            if m["status"] != "active" or prov_status.get(m["provider"]) != "active":
                continue
            if not any(r in m.get("roles", []) for r in roles):
                continue
            # The GMR "fast" lane means sub-100ms LOCAL response, not
            # cloud-fast: only Ollama residents qualify (cloud fast-role
            # models are reachable via the god-fast team instead).
            if domain == "fast" and m["provider"] != "ollama":
                continue
            local = m["provider"] == "ollama"
            registry_tier = m.get("tier") or 50
            benchmark_scores, benchmark_provenance = _benchmark_record(m, arena)
            entries.append({
                "model": m["id"],
                "provider": m["provider"],
                "tier": registry_tier,
                "policy_prior": {"registry_tier": registry_tier},
                "benchmark_scores": benchmark_scores,
                "benchmark_provenance": benchmark_provenance,
                "latency_ms": 50 if local else 500,
                # Free-tier cloud calls still burn provider quota: a nominal
                # nonzero cost keeps the rotator's cost-inverse scoring
                # local-first (the NEXUS SLM-team posture); true-local = 0.
                "cost_per_1m": 0.0 if local else 1.0,
                "status": "local" if local else "up",
            })
        # Sparse/fixture benchmark coverage must not silently reorder policy.
        entries.sort(key=lambda e: -e["tier"])
        # One slot per model FAMILY: the same frontier served by several
        # providers (e.g. DeepSeek-V4-Pro on baseten+siliconflow+nvidia)
        # must not crowd out distinct models; provider failover is the
        # rotator's job, not the domain list's.
        deduped, seen_ids = [], set()
        for e in entries:
            fam = e["model"].lower().rsplit("/", 1)[-1]
            for suffix in (":cloud", ":free", "-free"):
                fam = fam.removesuffix(suffix)
            if fam in seen_ids:
                continue
            seen_ids.add(fam)
            deduped.append(e)
        domains[domain] = {
            "primary": deduped[:6],
            "fallback_chain": [e["model"] for e in deduped[:4]],
        }
    return (
        f'"""{HEADER}"""\n\n'
        f"GENERATED_DOMAIN_MAPPING: dict = {_py_literal(domains)}\n"
    )


def _py_literal(obj) -> str:
    """JSON → Python literal (true/false/null → True/False/None)."""
    body = json.dumps(obj, indent=4, ensure_ascii=False, sort_keys=True)
    return (
        body.replace(": true", ": True")
        .replace(": false", ": False")
        .replace(": null", ": None")
    )


def emit_known_quotas(registry: dict) -> str:
    quotas = {}
    for slug in sorted(registry["providers"]):
        prov = registry["providers"][slug]
        quota = prov.get("quota") or {}
        if not isinstance(quota.get("windows"), dict):
            continue  # pre-v3 stragglers carry no structured block
        quotas[slug] = {
            "windows": quota["windows"],
            "tokens": quota.get("tokens", {}),
            "concurrent": quota.get("concurrent"),
            "burst": quota.get("burst"),
            "metering": quota.get("metering", "requests"),
            "credit": quota.get("credit", {}),
            "confidence": quota.get("confidence", "LOW"),
            "degradation": quota.get("degradation", "opaque"),
            "provider_status": prov.get("status"),
            "notes": quota.get("notes", ""),
        }
    quirks = registry.get("providerQuirks", {})
    return (
        f'"""{HEADER}"""\n\n'
        f"KNOWN_QUOTAS_GENERATED: dict = {_py_literal(quotas)}\n\n"
        f"PROVIDER_QUIRKS_GENERATED: dict = {_py_literal(quirks)}\n"
    )


def emit_license_map(registry: dict) -> str:
    providers = {}
    for slug in sorted(registry["providers"]):
        lic = registry["providers"][slug].get("outputLicense") or {}
        providers[slug] = lic.get("class", "unknown")
    overrides = {}
    for m in sorted(registry["models"], key=lambda x: (x["provider"], x["id"])):
        lic = m.get("outputLicense")
        if lic:
            overrides[f"{m['provider']}:{m['id']}"] = lic.get("class", "unknown")
    return (
        f'"""{HEADER}\n\n'
        "Trainability partition map (FI-T3). unknown NEVER resolves to\n"
        'permissive — a trace with unresolved license is reference-only."""\n\n'
        f"PROVIDER_LICENSE: dict[str, str] = {_py_literal(providers)}\n\n"
        f"MODEL_LICENSE_OVERRIDES: dict[str, str] = {_py_literal(overrides)}\n\n"
        "\n"
        "def license_class(provider: str, model_id: str) -> str:\n"
        '    """Effective outputLicense class for a (provider, model) pair."""\n'
        '    override = MODEL_LICENSE_OVERRIDES.get(f"{provider}:{model_id}")\n'
        "    if override:\n"
        "        return override\n"
        '    return PROVIDER_LICENSE.get(provider, "unknown")\n'
    )


def emit_scores(registry: dict, arena: dict) -> str:
    by_id: dict[str, dict] = {}
    provenance: dict[str, dict] = {}
    alias_of: dict[str, list] = {}

    for m in registry["models"]:
        dims, evidence = _benchmark_record(m, arena)
        existing = by_id.get(m["id"])
        # Duplicate model IDs can exist on several provider lanes. Preserve
        # the record with the richest independent evidence, then the stronger
        # dimension values; registry order breaks a full tie deterministically.
        if existing is not None and _evidence_rank(existing) >= _evidence_rank(dims):
            continue
        by_id[m["id"]] = dims
        provenance[m["id"]] = evidence

    for m in registry["models"]:
        for alias in m.get("aliases", []):
            alias_of.setdefault(alias, []).append(m["id"])
    scores: dict[str, dict] = dict(by_id)
    for alias, ids in sorted(alias_of.items()):
        best = max((by_id[i] for i in ids), key=_evidence_rank)
        current = scores.get(alias)
        if current is None or _evidence_rank(current) < _evidence_rank(best):
            scores[alias] = best
    doc = (
        "Independent benchmark dimensions from the committed arena snapshot"
        " (config/arena_scores.snapshot.json). Models or categories without"
        " cited measurements remain None/unscored. Registry tier is retained"
        " only as policy_prior.registry_tier and is never blended into or"
        " presented as benchmark evidence. Keys are every registry model id"
        " AND alias; SCORES_PROVENANCE records sources, confidence and as_of."
    )
    return f'''"""{HEADER}

{doc}"""

SCORES_GENERATED: dict = {_py_literal(scores)}

SCORES_PROVENANCE: dict = {_py_literal(provenance)}
'''


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="verify artifacts match the registry (drift test)")
    ap.add_argument("--only", default=None, help="comma-separated artifact subset to emit/check: ts, quota, chimera, ollama, domains, known_quotas, license, scores")
    args = ap.parse_args()

    registry = json.loads(REGISTRY.read_text(encoding="utf-8"))
    arena = _load_arena()
    named_outputs = {
        "ts": (TS_OUT, emit_ts(registry)),
        "quota": (QUOTA_OUT, emit_quota(registry)),
        "chimera": (CHIMERA_OUT, emit_chimera(registry, arena)),
        "ollama": (OLLAMA_OUT, emit_ollama(registry)),
        "domains": (DOMAINS_OUT, emit_domains(registry, arena)),
        "known_quotas": (QUOTAS_OUT, emit_known_quotas(registry)),
        "license": (LICENSE_OUT, emit_license_map(registry)),
        "scores": (SCORES_OUT, emit_scores(registry, arena)),
    }
    if args.only:
        wanted = [part.strip() for part in args.only.split(",") if part.strip()]
        unknown = sorted(set(wanted) - set(named_outputs))
        if unknown:
            ap.error("unknown artifact(s): " + ", ".join(unknown) + " (known: " + ", ".join(named_outputs) + ")")
        named_outputs = {k: v for k, v in named_outputs.items() if k in wanted}
    outputs = {path: content for path, content in named_outputs.values()}

    drift = []
    for path, content in outputs.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        if args.check:
            drift.append(path)
            if current is not None:
                diff = difflib.unified_diff(
                    current.splitlines()[:20], content.splitlines()[:20],
                    str(path), "regenerated", lineterm="",
                )
                print("\n".join(list(diff)[:30]))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
            print(f"wrote {path.relative_to(REPO)}")

    if args.check and drift:
        print(f"DRIFT: {len(drift)} artifact(s) stale — run scripts/gen_model_registry.py")
        return 1
    if args.check:
        print("registry artifacts in sync")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
