"""Generate routing tables from config/models.registry.json (single source of truth).

Emits four checked-in artifacts (deterministic — no timestamps — so a
byte-equality drift test can prove the registry and its consumers agree):

1. src/lib/modelrelay/config.generated.ts   — Node relay PROVIDERS/MODELS
2. nexus_os/relay/quota_limits_generated.py — context-window clamp table
3. nexus_os/twave/cloud_profiles_generated.json — Chimera cloud-tier profiles
4. nexus_os/relay/ollama_map_generated.py   — local/cloud Ollama model map

Usage:
    python scripts/gen_model_registry.py [--check]   # --check: exit 1 on drift
"""
from __future__ import annotations

import argparse
import difflib
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
REGISTRY = REPO / "config" / "models.registry.json"

TS_OUT = REPO / "src" / "lib" / "modelrelay" / "config.generated.ts"
QUOTA_OUT = REPO / "nexus_os" / "relay" / "quota_limits_generated.py"
CHIMERA_OUT = REPO / "nexus_os" / "twave" / "cloud_profiles_generated.json"
OLLAMA_OUT = REPO / "nexus_os" / "relay" / "ollama_map_generated.py"

HEADER = "GENERATED by scripts/gen_model_registry.py from config/models.registry.json — DO NOT EDIT (edit the registry, then regenerate)"

LOCAL_PROVIDERS = {"ollama"}


def _env_key(slug: str) -> str:
    return slug.upper().replace("-", "_") + "_API_KEY"


def _ts_provider(slug: str, prov: dict) -> dict:
    quota = prov.get("quota") or {}
    return {
        "id": slug,
        "name": slug,
        "provider": slug,
        "baseUrl": prov["baseUrl"].rstrip("/"),
        "chatPath": prov.get("chatPath", "/chat/completions"),
        "modelsPath": prov.get("modelsPath", "/models"),
        "authType": "x-api-key" if prov.get("authHeader", "").lower() == "x-goog-api-key" else ("none" if prov.get("keyRef") is None else "bearer"),
        "quotaType": "free_tier",
        "quotaRemaining": quota.get("rpm", -1) if isinstance(quota.get("rpm"), int) else "varies",
        "costPer1m": 0.0,
        "latencyMs": 400,
        "status": "up" if prov["status"] == "active" else "down",
        "tier": 50,
        "priority": prov.get("priority", 50),
        "isFree": True,
        "isLocal": slug in LOCAL_PROVIDERS,
        "models": [],
        "envKey": _env_key(slug),
        "keyRef": prov.get("keyRef"),
    }


def _ts_model(m: dict) -> dict:
    caps = m.get("capabilities") or {}
    active = m["status"] == "active"
    return {
        "modelId": f"{m['provider']}/{m['id']}",
        "provider": m["provider"],
        "name": m["id"],
        "tier": m.get("tier") or 50,
        "costPer1mInput": 0,
        "costPer1mOutput": 0,
        "contextWindow": m.get("context") or 32768,
        "latencyMsTypical": 500,
        "supportsVision": bool(caps.get("vision")),
        "supportsFunctionCalling": bool(caps.get("tools")),
        "supportsStreaming": True,
        "isFree": m.get("free") is not False,
        "isLocal": m["provider"] in LOCAL_PROVIDERS,
        "status": "up" if active else "down",
    }


def emit_ts(registry: dict) -> str:
    providers = {}
    for slug in sorted(registry["providers"]):
        prov = registry["providers"][slug]
        if not prov.get("baseUrl"):
            continue  # discovery-only providers stay on the npm relay / legacy config
        if prov["status"] == "deprecated":
            continue
        providers[slug] = _ts_provider(slug, prov)

    prov_status = {k: v["status"] for k, v in registry["providers"].items()}
    models = []
    for m in sorted(registry["models"], key=lambda x: (x["provider"], x["id"])):
        if m["provider"] not in providers:
            continue
        entry = _ts_model(m)
        if prov_status.get(m["provider"]) != "active":
            entry["status"] = "down"
        models.append(entry)
        providers[m["provider"]]["models"].append(m["id"])

    deprecated = sorted(
        slug for slug, p in registry["providers"].items() if p["status"] == "deprecated"
    )

    lines = [
        "/**",
        f" * {HEADER}",
        " */",
        "import type { ProviderConfig, ModelInfo } from './config'",
        "",
        "export const REGISTRY_VERSION = %d" % registry["version"],
        "",
        "// Providers the registry retired — the merge facade must drop their",
        "// legacy config.ts entries (e.g. the dead keyless zai/glm-5.2 block).",
        "export const DEPRECATED_PROVIDERS: string[] = " + json.dumps(deprecated),
        "",
        "export const PROVIDERS_GENERATED: Record<string, ProviderConfig & { keyRef?: string | null }> = "
        + json.dumps(providers, indent=2, ensure_ascii=False),
        "",
        "export const MODELS_GENERATED: ModelInfo[] = "
        + json.dumps(models, indent=2, ensure_ascii=False),
        "",
    ]
    return "\n".join(lines)


def emit_quota(registry: dict) -> str:
    limits: dict[str, int] = {}
    for m in registry["models"]:
        ctx = m.get("context")
        if not ctx:
            continue
        for key in (m["id"], *m.get("aliases", [])):
            existing = limits.get(key)
            # Conservative on collision: the SMALLEST window wins so the
            # clamp can never overshoot the real provider limit.
            limits[key] = min(existing, ctx) if existing else ctx
    body = json.dumps(dict(sorted(limits.items())), indent=4, ensure_ascii=False)
    # JSON -> Python literal (true/false/null never appear in this int map)
    return (
        f'"""{HEADER}"""\n\n'
        f"KNOWN_CONTEXT_LIMITS: dict[str, int] = {body}\n"
    )


def emit_chimera(registry: dict) -> str:
    prov_status = {k: v["status"] for k, v in registry["providers"].items()}
    profiles = []
    seen = set()
    for m in sorted(registry["models"], key=lambda x: -(x.get("tier") or 0)):
        if m["status"] != "active" or prov_status.get(m["provider"]) != "active":
            continue
        if m["provider"] in LOCAL_PROVIDERS:
            continue  # local hardware profiles stay hand-authored in chimera
        if "frontier" not in m.get("roles", []) and "reasoning" not in m.get("roles", []) and "code" not in m.get("roles", []):
            continue
        if m["id"] in seen:
            continue
        seen.add(m["id"])
        caps = m.get("capabilities") or {}
        profiles.append({
            "name": m["id"],
            "provider": m["provider"],
            "quality_score": round((m.get("tier") or 50) / 100.0, 2),
            "max_context": m.get("context") or 32768,
            "supports_thinking": bool(caps.get("thinking")),
            "roles": m.get("roles", []),
        })
    return json.dumps({"_comment": HEADER, "cloud_profiles": profiles}, indent=2, ensure_ascii=False) + "\n"


def emit_ollama(registry: dict) -> str:
    mapping: dict[str, str] = {}
    cloud: list[str] = []
    for m in registry["models"]:
        if m["provider"] == "ollama":
            for alias in m.get("aliases", []):
                mapping[alias] = m["id"]
            mapping[m["id"]] = m["id"]
        elif m["provider"] == "ollama-cloud":
            cloud.append(m["id"])
            for alias in m.get("aliases", []):
                mapping[alias] = m["id"]
    return (
        f'"""{HEADER}"""\n\n'
        f"OLLAMA_MODEL_MAP: dict[str, str] = {json.dumps(dict(sorted(mapping.items())), indent=4, ensure_ascii=False)}\n\n"
        f"OLLAMA_CLOUD_MODELS: list[str] = {json.dumps(sorted(set(cloud)), indent=4, ensure_ascii=False)}\n"
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="verify artifacts match the registry (drift test)")
    args = ap.parse_args()

    registry = json.loads(REGISTRY.read_text(encoding="utf-8"))
    outputs = {
        TS_OUT: emit_ts(registry),
        QUOTA_OUT: emit_quota(registry),
        CHIMERA_OUT: emit_chimera(registry),
        OLLAMA_OUT: emit_ollama(registry),
    }

    drift = []
    for path, content in outputs.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        if args.check:
            drift.append(path)
            if current is not None:
                diff = difflib.unified_diff(
                    current.splitlines()[:20], content.splitlines()[:20],
                    str(path), "regenerated", lineterm="",
                )
                print("\n".join(list(diff)[:30]))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
            print(f"wrote {path.relative_to(REPO)}")

    if args.check and drift:
        print(f"DRIFT: {len(drift)} artifact(s) stale — run scripts/gen_model_registry.py")
        return 1
    if args.check:
        print("registry artifacts in sync")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
