"""GENERATED by scripts/gen_model_registry.py from config/models.registry.json — DO NOT EDIT (edit the registry, then regenerate)"""

OLLAMA_MODEL_MAP: dict[str, str] = {
    "VibeThinker-3B": "vibethinker-3b",
    "functiongemma-270m": "functiongemma:latest",
    "functiongemma:latest": "functiongemma:latest",
    "minimax-m2.7": "minimax-m2.7",
    "nemotron-3-nano:4b": "nemotron-3-nano:4b",
    "qwen2.5-coder:7b": "qwen2.5-coder:7b",
    "vibethinker-3b": "vibethinker-3b"
}

OLLAMA_CLOUD_MODELS: list[str] = [
    "glm-4.7",
    "minimax-m3:cloud",
    "qwen3-coder:480b"
]
