"""GENERATED by scripts/gen_model_registry.py from config/models.registry.json — DO NOT EDIT (edit the registry, then regenerate)

Blended capability scores: registry tier fused with the committed arena snapshot (config/arena_scores.snapshot.json). Keys are every registry model id AND alias; SCORES_PROVENANCE (registry ids only) records components, weights, sources and as_of per model."""

SCORES_GENERATED: dict = {
    "LongCat-2.0": {
        "code": 0.93,
        "cost_efficiency": 1.0,
        "quality": 0.93,
        "reasoning": 0.93,
        "speed": 0.5,
        "swe": 0.93
    },
    "MiniMaxAI/MiniMax-M2.1": {
        "code": 0.8,
        "cost_efficiency": 1.0,
        "quality": 0.8,
        "reasoning": 0.8,
        "speed": 0.5,
        "swe": 0.8
    },
    "MiniMaxAI/MiniMax-M2.5": {
        "code": 0.84,
        "cost_efficiency": 1.0,
        "quality": 0.84,
        "reasoning": 0.84,
        "speed": 0.5,
        "swe": 0.84
    },
    "MiniMaxAI/MiniMax-M3": {
        "code": 0.8937,
        "cost_efficiency": 1.0,
        "quality": 0.8937,
        "reasoning": 0.8937,
        "speed": 0.5,
        "swe": 0.8937
    },
    "Qwen/Qwen3-235B-A22B": {
        "code": 0.85,
        "cost_efficiency": 1.0,
        "quality": 0.85,
        "reasoning": 0.85,
        "speed": 0.5,
        "swe": 0.85
    },
    "Qwen/Qwen3-32B": {
        "code": 0.72,
        "cost_efficiency": 1.0,
        "quality": 0.72,
        "reasoning": 0.72,
        "speed": 0.5,
        "swe": 0.72
    },
    "VibeThinker-3B": {
        "code": 0.45,
        "cost_efficiency": 1.0,
        "quality": 0.45,
        "reasoning": 0.45,
        "speed": 0.5,
        "swe": 0.45
    },
    "deepseek-ai/DeepSeek-V4-Flash": {
        "code": 0.92,
        "cost_efficiency": 1.0,
        "quality": 0.92,
        "reasoning": 0.92,
        "speed": 0.5,
        "swe": 0.92
    },
    "deepseek-ai/DeepSeek-V4-Pro": {
        "code": 0.95,
        "cost_efficiency": 1.0,
        "quality": 0.95,
        "reasoning": 0.95,
        "speed": 0.5,
        "swe": 0.95
    },
    "deepseek-ai/deepseek-v4-flash": {
        "code": 0.92,
        "cost_efficiency": 1.0,
        "quality": 0.92,
        "reasoning": 0.92,
        "speed": 0.5,
        "swe": 0.92
    },
    "deepseek-ai/deepseek-v4-pro": {
        "code": 0.95,
        "cost_efficiency": 1.0,
        "quality": 0.95,
        "reasoning": 0.95,
        "speed": 0.5,
        "swe": 0.95
    },
    "deepseek-v4-flash": {
        "code": 0.92,
        "cost_efficiency": 1.0,
        "quality": 0.92,
        "reasoning": 0.92,
        "speed": 0.5,
        "swe": 0.92
    },
    "deepseek-v4-flash-free": {
        "code": 0.92,
        "cost_efficiency": 1.0,
        "quality": 0.92,
        "reasoning": 0.92,
        "speed": 0.5,
        "swe": 0.92
    },
    "deepseek-v4-pro": {
        "code": 0.95,
        "cost_efficiency": 1.0,
        "quality": 0.95,
        "reasoning": 0.95,
        "speed": 0.5,
        "swe": 0.95
    },
    "functiongemma-270m": {
        "code": 0.3,
        "cost_efficiency": 1.0,
        "quality": 0.3,
        "reasoning": 0.3,
        "speed": 0.5,
        "swe": 0.3
    },
    "functiongemma:latest": {
        "code": 0.3,
        "cost_efficiency": 1.0,
        "quality": 0.3,
        "reasoning": 0.3,
        "speed": 0.5,
        "swe": 0.3
    },
    "glm-4.7": {
        "code": 0.82,
        "cost_efficiency": 1.0,
        "quality": 0.82,
        "reasoning": 0.82,
        "speed": 0.5,
        "swe": 0.82
    },
    "glm-5.2": {
        "code": 0.917,
        "cost_efficiency": 1.0,
        "quality": 0.96,
        "reasoning": 0.96,
        "speed": 0.5,
        "swe": 0.917
    },
    "intern-latest": {
        "code": 0.8,
        "cost_efficiency": 1.0,
        "quality": 0.8,
        "reasoning": 0.8,
        "speed": 0.5,
        "swe": 0.8
    },
    "intern-s1": {
        "code": 0.75,
        "cost_efficiency": 1.0,
        "quality": 0.75,
        "reasoning": 0.75,
        "speed": 0.5,
        "swe": 0.75
    },
    "intern-s1-mini": {
        "code": 0.7,
        "cost_efficiency": 1.0,
        "quality": 0.7,
        "reasoning": 0.7,
        "speed": 0.5,
        "swe": 0.7
    },
    "intern-s1-pro": {
        "code": 0.82,
        "cost_efficiency": 1.0,
        "quality": 0.82,
        "reasoning": 0.82,
        "speed": 0.5,
        "swe": 0.82
    },
    "intern-s2-preview": {
        "code": 0.85,
        "cost_efficiency": 1.0,
        "quality": 0.85,
        "reasoning": 0.85,
        "speed": 0.5,
        "swe": 0.85
    },
    "internvl-latest": {
        "code": 0.72,
        "cost_efficiency": 1.0,
        "quality": 0.72,
        "reasoning": 0.72,
        "speed": 0.5,
        "swe": 0.72
    },
    "internvl3.5-241b-a28b": {
        "code": 0.78,
        "cost_efficiency": 1.0,
        "quality": 0.78,
        "reasoning": 0.78,
        "speed": 0.5,
        "swe": 0.78
    },
    "internvl3.5-latest": {
        "code": 0.7,
        "cost_efficiency": 1.0,
        "quality": 0.7,
        "reasoning": 0.7,
        "speed": 0.5,
        "swe": 0.7
    },
    "kilo-auto/free": {
        "code": 0.6,
        "cost_efficiency": 1.0,
        "quality": 0.6,
        "reasoning": 0.6,
        "speed": 0.5,
        "swe": 0.6
    },
    "kimi-k2-thinking": {
        "code": 0.88,
        "cost_efficiency": 1.0,
        "quality": 0.88,
        "reasoning": 0.88,
        "speed": 0.5,
        "swe": 0.88
    },
    "kimi-k2.6": {
        "code": 0.791,
        "cost_efficiency": 1.0,
        "quality": 0.8601,
        "reasoning": 0.8601,
        "speed": 0.5,
        "swe": 0.791
    },
    "kimi-k2.7-code": {
        "code": 0.94,
        "cost_efficiency": 0.2,
        "quality": 0.94,
        "reasoning": 0.94,
        "speed": 0.5,
        "swe": 0.94
    },
    "mimo-v2.5": {
        "code": 0.82,
        "cost_efficiency": 1.0,
        "quality": 0.82,
        "reasoning": 0.82,
        "speed": 0.5,
        "swe": 0.82
    },
    "mimo-v2.5-free": {
        "code": 0.82,
        "cost_efficiency": 1.0,
        "quality": 0.82,
        "reasoning": 0.82,
        "speed": 0.5,
        "swe": 0.82
    },
    "minimax-m2.7": {
        "code": 0.6,
        "cost_efficiency": 1.0,
        "quality": 0.6,
        "reasoning": 0.6,
        "speed": 0.5,
        "swe": 0.6
    },
    "minimax-m3": {
        "code": 0.8937,
        "cost_efficiency": 1.0,
        "quality": 0.8937,
        "reasoning": 0.8937,
        "speed": 0.5,
        "swe": 0.8937
    },
    "minimax-m3:cloud": {
        "code": 0.8937,
        "cost_efficiency": 1.0,
        "quality": 0.8937,
        "reasoning": 0.8937,
        "speed": 0.5,
        "swe": 0.8937
    },
    "minimaxai/minimax-m2.7": {
        "code": 0.82,
        "cost_efficiency": 1.0,
        "quality": 0.82,
        "reasoning": 0.82,
        "speed": 0.5,
        "swe": 0.82
    },
    "minimaxai/minimax-m3": {
        "code": 0.8937,
        "cost_efficiency": 1.0,
        "quality": 0.8937,
        "reasoning": 0.8937,
        "speed": 0.5,
        "swe": 0.8937
    },
    "moonshotai/Kimi-K2-Instruct": {
        "code": 0.8,
        "cost_efficiency": 1.0,
        "quality": 0.8,
        "reasoning": 0.8,
        "speed": 0.5,
        "swe": 0.8
    },
    "moonshotai/Kimi-K2-Thinking": {
        "code": 0.88,
        "cost_efficiency": 1.0,
        "quality": 0.88,
        "reasoning": 0.88,
        "speed": 0.5,
        "swe": 0.88
    },
    "moonshotai/Kimi-K2.5": {
        "code": 0.86,
        "cost_efficiency": 0.2,
        "quality": 0.86,
        "reasoning": 0.86,
        "speed": 0.5,
        "swe": 0.86
    },
    "moonshotai/Kimi-K2.6": {
        "code": 0.791,
        "cost_efficiency": 1.0,
        "quality": 0.8601,
        "reasoning": 0.8601,
        "speed": 0.5,
        "swe": 0.791
    },
    "moonshotai/Kimi-K2.7-Code": {
        "code": 0.94,
        "cost_efficiency": 0.2,
        "quality": 0.94,
        "reasoning": 0.94,
        "speed": 0.5,
        "swe": 0.94
    },
    "moonshotai/kimi-k2-thinking": {
        "code": 0.88,
        "cost_efficiency": 1.0,
        "quality": 0.88,
        "reasoning": 0.88,
        "speed": 0.5,
        "swe": 0.88
    },
    "moonshotai/kimi-k2.6": {
        "code": 0.791,
        "cost_efficiency": 1.0,
        "quality": 0.8601,
        "reasoning": 0.8601,
        "speed": 0.5,
        "swe": 0.791
    },
    "nemotron-3-nano-omni-30b-reasoning": {
        "code": 0.85,
        "cost_efficiency": 1.0,
        "quality": 0.85,
        "reasoning": 0.85,
        "speed": 0.5,
        "swe": 0.85
    },
    "nemotron-3-nano:4b": {
        "code": 0.45,
        "cost_efficiency": 1.0,
        "quality": 0.45,
        "reasoning": 0.45,
        "speed": 0.5,
        "swe": 0.45
    },
    "nemotron-3-super": {
        "code": 0.8,
        "cost_efficiency": 1.0,
        "quality": 0.8,
        "reasoning": 0.8,
        "speed": 0.5,
        "swe": 0.8
    },
    "nemotron-3-ultra": {
        "code": 0.88,
        "cost_efficiency": 1.0,
        "quality": 0.88,
        "reasoning": 0.88,
        "speed": 0.5,
        "swe": 0.88
    },
    "nemotron-3-ultra-free": {
        "code": 0.88,
        "cost_efficiency": 1.0,
        "quality": 0.88,
        "reasoning": 0.88,
        "speed": 0.5,
        "swe": 0.88
    },
    "north-mini-code-free": {
        "code": 0.7,
        "cost_efficiency": 1.0,
        "quality": 0.7,
        "reasoning": 0.7,
        "speed": 0.5,
        "swe": 0.7
    },
    "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B": {
        "code": 0.88,
        "cost_efficiency": 0.2,
        "quality": 0.88,
        "reasoning": 0.88,
        "speed": 0.5,
        "swe": 0.88
    },
    "nvidia/Nemotron-120B-A12B": {
        "code": 0.75,
        "cost_efficiency": 0.2,
        "quality": 0.75,
        "reasoning": 0.75,
        "speed": 0.5,
        "swe": 0.75
    },
    "nvidia/devstral-2-123b": {
        "code": 0.82,
        "cost_efficiency": 1.0,
        "quality": 0.82,
        "reasoning": 0.82,
        "speed": 0.5,
        "swe": 0.82
    },
    "nvidia/llama-3.1-nemotron-ultra-253b-v1": {
        "code": 0.5,
        "cost_efficiency": 1.0,
        "quality": 0.5,
        "reasoning": 0.5,
        "speed": 0.5,
        "swe": 0.5
    },
    "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning": {
        "code": 0.85,
        "cost_efficiency": 1.0,
        "quality": 0.85,
        "reasoning": 0.85,
        "speed": 0.5,
        "swe": 0.85
    },
    "nvidia/nemotron-3-super-120b-a12b": {
        "code": 0.8,
        "cost_efficiency": 1.0,
        "quality": 0.8,
        "reasoning": 0.8,
        "speed": 0.5,
        "swe": 0.8
    },
    "nvidia/nemotron-3-super-120b-a12b:free": {
        "code": 0.8,
        "cost_efficiency": 1.0,
        "quality": 0.8,
        "reasoning": 0.8,
        "speed": 0.5,
        "swe": 0.8
    },
    "nvidia/nemotron-3-ultra-550b-a55b": {
        "code": 0.88,
        "cost_efficiency": 1.0,
        "quality": 0.88,
        "reasoning": 0.88,
        "speed": 0.5,
        "swe": 0.88
    },
    "openai/gpt-oss-120b": {
        "code": 0.78,
        "cost_efficiency": 0.2,
        "quality": 0.78,
        "reasoning": 0.78,
        "speed": 0.5,
        "swe": 0.78
    },
    "poolside/laguna-m.1:free": {
        "code": 0.7,
        "cost_efficiency": 1.0,
        "quality": 0.7,
        "reasoning": 0.7,
        "speed": 0.5,
        "swe": 0.7
    },
    "qwen/qwen3-next-80b-a3b-instruct": {
        "code": 0.84,
        "cost_efficiency": 1.0,
        "quality": 0.84,
        "reasoning": 0.84,
        "speed": 0.5,
        "swe": 0.84
    },
    "qwen/qwen3.5-122b-a10b": {
        "code": 0.8,
        "cost_efficiency": 1.0,
        "quality": 0.8,
        "reasoning": 0.8,
        "speed": 0.5,
        "swe": 0.8
    },
    "qwen/qwen3.5-397b-a17b": {
        "code": 0.86,
        "cost_efficiency": 1.0,
        "quality": 0.86,
        "reasoning": 0.86,
        "speed": 0.5,
        "swe": 0.86
    },
    "qwen2.5-coder:7b": {
        "code": 0.48,
        "cost_efficiency": 1.0,
        "quality": 0.48,
        "reasoning": 0.48,
        "speed": 0.5,
        "swe": 0.48
    },
    "qwen3-coder:480b": {
        "code": 0.86,
        "cost_efficiency": 1.0,
        "quality": 0.86,
        "reasoning": 0.86,
        "speed": 0.5,
        "swe": 0.86
    },
    "qwen3-next-80b": {
        "code": 0.84,
        "cost_efficiency": 1.0,
        "quality": 0.84,
        "reasoning": 0.84,
        "speed": 0.5,
        "swe": 0.84
    },
    "qwen3.5-397b": {
        "code": 0.86,
        "cost_efficiency": 1.0,
        "quality": 0.86,
        "reasoning": 0.86,
        "speed": 0.5,
        "swe": 0.86
    },
    "qwen3.6-plus-free": {
        "code": 0.84,
        "cost_efficiency": 1.0,
        "quality": 0.84,
        "reasoning": 0.84,
        "speed": 0.5,
        "swe": 0.84
    },
    "step-3.7-flash": {
        "code": 0.84,
        "cost_efficiency": 1.0,
        "quality": 0.84,
        "reasoning": 0.84,
        "speed": 0.5,
        "swe": 0.84
    },
    "stepfun-ai/step-3.5-flash": {
        "code": 0.76,
        "cost_efficiency": 1.0,
        "quality": 0.76,
        "reasoning": 0.76,
        "speed": 0.5,
        "swe": 0.76
    },
    "stepfun-ai/step-3.7-flash": {
        "code": 0.84,
        "cost_efficiency": 1.0,
        "quality": 0.84,
        "reasoning": 0.84,
        "speed": 0.5,
        "swe": 0.84
    },
    "stepfun/step-3.7-flash": {
        "code": 0.84,
        "cost_efficiency": 1.0,
        "quality": 0.84,
        "reasoning": 0.84,
        "speed": 0.5,
        "swe": 0.84
    },
    "stepfun/step-3.7-flash:free": {
        "code": 0.84,
        "cost_efficiency": 1.0,
        "quality": 0.84,
        "reasoning": 0.84,
        "speed": 0.5,
        "swe": 0.84
    },
    "vibethinker-3b": {
        "code": 0.45,
        "cost_efficiency": 1.0,
        "quality": 0.45,
        "reasoning": 0.45,
        "speed": 0.5,
        "swe": 0.45
    },
    "z-ai/glm-5.1": {
        "code": 0.91,
        "cost_efficiency": 1.0,
        "quality": 0.91,
        "reasoning": 0.91,
        "speed": 0.5,
        "swe": 0.91
    },
    "z-ai/glm-5.2": {
        "code": 0.917,
        "cost_efficiency": 1.0,
        "quality": 0.96,
        "reasoning": 0.96,
        "speed": 0.5,
        "swe": 0.917
    },
    "zai-org/GLM-4.5": {
        "code": 0.78,
        "cost_efficiency": 1.0,
        "quality": 0.78,
        "reasoning": 0.78,
        "speed": 0.5,
        "swe": 0.78
    },
    "zai-org/GLM-4.7": {
        "code": 0.82,
        "cost_efficiency": 0.2,
        "quality": 0.82,
        "reasoning": 0.82,
        "speed": 0.5,
        "swe": 0.82
    },
    "zai-org/GLM-5": {
        "code": 0.89,
        "cost_efficiency": 1.0,
        "quality": 0.89,
        "reasoning": 0.89,
        "speed": 0.5,
        "swe": 0.89
    },
    "zai-org/GLM-5.1": {
        "code": 0.91,
        "cost_efficiency": 1.0,
        "quality": 0.91,
        "reasoning": 0.91,
        "speed": 0.5,
        "swe": 0.91
    },
    "zai-org/GLM-5.2": {
        "code": 0.917,
        "cost_efficiency": 1.0,
        "quality": 0.9565,
        "reasoning": 0.9565,
        "speed": 0.5,
        "swe": 0.917
    }
}

SCORES_PROVENANCE: dict = {
    "LongCat-2.0": {
        "as_of": None,
        "components": {
            "tier": 93
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "MiniMaxAI/MiniMax-M2.1": {
        "as_of": None,
        "components": {
            "tier": 80
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "MiniMaxAI/MiniMax-M2.5": {
        "as_of": None,
        "components": {
            "tier": 84
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "MiniMaxAI/MiniMax-M3": {
        "as_of": "2026-07-08T00:00:00+00:00",
        "components": {
            "arena_calibrated": 0.8903,
            "arena_score": 0.6641,
            "calibration_scale": 1.3406,
            "internal_bench": None,
            "tier": 90
        },
        "provenance": "arena+tier",
        "sources": [
            "aa_intelligence_index",
            "aa_speed",
            "lmarena_elo"
        ],
        "weights": {
            "arena": 0.6471,
            "tier": 0.3529
        }
    },
    "Qwen/Qwen3-235B-A22B": {
        "as_of": None,
        "components": {
            "tier": 85
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "Qwen/Qwen3-32B": {
        "as_of": None,
        "components": {
            "tier": 72
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "deepseek-ai/DeepSeek-V4-Flash": {
        "as_of": None,
        "components": {
            "tier": 92
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "deepseek-ai/DeepSeek-V4-Pro": {
        "as_of": None,
        "components": {
            "tier": 95
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "deepseek-ai/deepseek-v4-flash": {
        "as_of": None,
        "components": {
            "tier": 92
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "deepseek-ai/deepseek-v4-pro": {
        "as_of": None,
        "components": {
            "tier": 95
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "deepseek-v4-flash": {
        "as_of": None,
        "components": {
            "tier": 92
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "deepseek-v4-flash-free": {
        "as_of": None,
        "components": {
            "tier": 92
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "functiongemma:latest": {
        "as_of": None,
        "components": {
            "tier": 30
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "glm-4.7": {
        "as_of": None,
        "components": {
            "tier": 82
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "intern-latest": {
        "as_of": None,
        "components": {
            "tier": 80
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "intern-s1": {
        "as_of": None,
        "components": {
            "tier": 75
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "intern-s1-mini": {
        "as_of": None,
        "components": {
            "tier": 70
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "intern-s1-pro": {
        "as_of": None,
        "components": {
            "tier": 82
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "intern-s2-preview": {
        "as_of": None,
        "components": {
            "tier": 85
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "internvl-latest": {
        "as_of": None,
        "components": {
            "tier": 72
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "internvl3.5-241b-a28b": {
        "as_of": None,
        "components": {
            "tier": 78
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "internvl3.5-latest": {
        "as_of": None,
        "components": {
            "tier": 70
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "kilo-auto/free": {
        "as_of": None,
        "components": {
            "tier": 60
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "mimo-v2.5-free": {
        "as_of": None,
        "components": {
            "tier": 82
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "minimax-m2.7": {
        "as_of": None,
        "components": {
            "tier": 60
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "minimax-m3:cloud": {
        "as_of": "2026-07-08T00:00:00+00:00",
        "components": {
            "arena_calibrated": 0.8903,
            "arena_score": 0.6641,
            "calibration_scale": 1.3406,
            "internal_bench": None,
            "tier": 90
        },
        "provenance": "arena+tier",
        "sources": [
            "aa_intelligence_index",
            "aa_speed",
            "lmarena_elo"
        ],
        "weights": {
            "arena": 0.6471,
            "tier": 0.3529
        }
    },
    "minimaxai/minimax-m2.7": {
        "as_of": None,
        "components": {
            "tier": 82
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "minimaxai/minimax-m3": {
        "as_of": "2026-07-08T00:00:00+00:00",
        "components": {
            "arena_calibrated": 0.8903,
            "arena_score": 0.6641,
            "calibration_scale": 1.3406,
            "internal_bench": None,
            "tier": 90
        },
        "provenance": "arena+tier",
        "sources": [
            "aa_intelligence_index",
            "aa_speed",
            "lmarena_elo"
        ],
        "weights": {
            "arena": 0.6471,
            "tier": 0.3529
        }
    },
    "moonshotai/Kimi-K2-Instruct": {
        "as_of": None,
        "components": {
            "tier": 80
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "moonshotai/Kimi-K2-Thinking": {
        "as_of": None,
        "components": {
            "tier": 88
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "moonshotai/Kimi-K2.5": {
        "as_of": None,
        "components": {
            "tier": 86
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "moonshotai/Kimi-K2.6": {
        "as_of": "2026-07-08T00:00:00+00:00",
        "components": {
            "arena_calibrated": 0.8383,
            "arena_score": 0.6253,
            "calibration_scale": 1.3406,
            "internal_bench": None,
            "tier": 90
        },
        "provenance": "arena+tier",
        "sources": [
            "aa_coding",
            "aa_intelligence_index",
            "aa_price",
            "aa_speed",
            "lmarena_code_elo",
            "lmarena_elo"
        ],
        "weights": {
            "arena": 0.6471,
            "tier": 0.3529
        }
    },
    "moonshotai/Kimi-K2.7-Code": {
        "as_of": None,
        "components": {
            "tier": 94
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "moonshotai/kimi-k2-thinking": {
        "as_of": None,
        "components": {
            "tier": 88
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "moonshotai/kimi-k2.6": {
        "as_of": "2026-07-08T00:00:00+00:00",
        "components": {
            "arena_calibrated": 0.8383,
            "arena_score": 0.6253,
            "calibration_scale": 1.3406,
            "internal_bench": None,
            "tier": 90
        },
        "provenance": "arena+tier",
        "sources": [
            "aa_coding",
            "aa_intelligence_index",
            "aa_price",
            "aa_speed",
            "lmarena_code_elo",
            "lmarena_elo"
        ],
        "weights": {
            "arena": 0.6471,
            "tier": 0.3529
        }
    },
    "nemotron-3-nano:4b": {
        "as_of": None,
        "components": {
            "tier": 45
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "nemotron-3-ultra-free": {
        "as_of": None,
        "components": {
            "tier": 88
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "north-mini-code-free": {
        "as_of": None,
        "components": {
            "tier": 70
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B": {
        "as_of": None,
        "components": {
            "tier": 88
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "nvidia/Nemotron-120B-A12B": {
        "as_of": None,
        "components": {
            "tier": 75
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "nvidia/devstral-2-123b": {
        "as_of": None,
        "components": {
            "tier": 82
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "nvidia/llama-3.1-nemotron-ultra-253b-v1": {
        "as_of": None,
        "components": {
            "tier": 50
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning": {
        "as_of": None,
        "components": {
            "tier": 85
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "nvidia/nemotron-3-super-120b-a12b": {
        "as_of": None,
        "components": {
            "tier": 80
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "nvidia/nemotron-3-super-120b-a12b:free": {
        "as_of": None,
        "components": {
            "tier": 80
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "nvidia/nemotron-3-ultra-550b-a55b": {
        "as_of": None,
        "components": {
            "tier": 88
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "openai/gpt-oss-120b": {
        "as_of": None,
        "components": {
            "tier": 78
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "poolside/laguna-m.1:free": {
        "as_of": None,
        "components": {
            "tier": 70
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "qwen/qwen3-next-80b-a3b-instruct": {
        "as_of": None,
        "components": {
            "tier": 84
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "qwen/qwen3.5-122b-a10b": {
        "as_of": None,
        "components": {
            "tier": 80
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "qwen/qwen3.5-397b-a17b": {
        "as_of": None,
        "components": {
            "tier": 86
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "qwen2.5-coder:7b": {
        "as_of": None,
        "components": {
            "tier": 48
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "qwen3-coder:480b": {
        "as_of": None,
        "components": {
            "tier": 86
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "qwen3.6-plus-free": {
        "as_of": None,
        "components": {
            "tier": 84
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "stepfun-ai/step-3.5-flash": {
        "as_of": None,
        "components": {
            "tier": 76
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "stepfun-ai/step-3.7-flash": {
        "as_of": None,
        "components": {
            "tier": 84
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "stepfun/step-3.7-flash:free": {
        "as_of": None,
        "components": {
            "tier": 84
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "vibethinker-3b": {
        "as_of": None,
        "components": {
            "tier": 45
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "z-ai/glm-5.1": {
        "as_of": None,
        "components": {
            "tier": 91
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "z-ai/glm-5.2": {
        "as_of": "2026-07-08T00:00:00+00:00",
        "components": {
            "arena_calibrated": 0.96,
            "arena_score": 0.7161,
            "calibration_scale": 1.3406,
            "internal_bench": None,
            "tier": 96
        },
        "provenance": "arena+tier",
        "sources": [
            "aa_coding",
            "aa_intelligence_index",
            "aa_price",
            "aa_speed",
            "lmarena_code_elo",
            "lmarena_elo"
        ],
        "weights": {
            "arena": 0.6471,
            "tier": 0.3529
        }
    },
    "zai-org/GLM-4.5": {
        "as_of": None,
        "components": {
            "tier": 78
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "zai-org/GLM-4.7": {
        "as_of": None,
        "components": {
            "tier": 82
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "zai-org/GLM-5": {
        "as_of": None,
        "components": {
            "tier": 89
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "zai-org/GLM-5.1": {
        "as_of": None,
        "components": {
            "tier": 91
        },
        "provenance": "tier-only",
        "sources": [],
        "weights": {
            "tier": 1.0
        }
    },
    "zai-org/GLM-5.2": {
        "as_of": "2026-07-08T00:00:00+00:00",
        "components": {
            "arena_calibrated": 0.96,
            "arena_score": 0.7161,
            "calibration_scale": 1.3406,
            "internal_bench": None,
            "tier": 95
        },
        "provenance": "arena+tier",
        "sources": [
            "aa_coding",
            "aa_intelligence_index",
            "aa_price",
            "aa_speed",
            "lmarena_code_elo",
            "lmarena_elo"
        ],
        "weights": {
            "arena": 0.6471,
            "tier": 0.3529
        }
    }
}
