"""GENERATED by scripts/gen_model_registry.py from config/models.registry.json — DO NOT EDIT (edit the registry, then regenerate)

Independent benchmark dimensions from the committed arena snapshot (config/arena_scores.snapshot.json). Models or categories without cited measurements remain None/unscored. Registry tier is retained only as policy_prior.registry_tier and is never blended into or presented as benchmark evidence. Keys are every registry model id AND alias; SCORES_PROVENANCE records sources, confidence and as_of."""

SCORES_GENERATED: dict = {
    "LongCat-2.0": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "MiniMaxAI/MiniMax-M2.1": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "MiniMaxAI/MiniMax-M2.5": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "MiniMaxAI/MiniMax-M3": {
        "code": None,
        "cost_efficiency": None,
        "quality": 0.6641,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "Qwen/Qwen3-235B-A22B": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "Qwen/Qwen3-32B": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "VibeThinker-3B": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "deepseek-ai/DeepSeek-V4-Flash": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "deepseek-ai/DeepSeek-V4-Pro": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "deepseek-ai/deepseek-v4-flash": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "deepseek-ai/deepseek-v4-pro": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "deepseek-v4-flash": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "deepseek-v4-flash-free": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "deepseek-v4-pro": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "functiongemma-270m": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "functiongemma:latest": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "glm-4.7": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "glm-5.2": {
        "code": 0.684,
        "cost_efficiency": None,
        "quality": 0.7161,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "intern-latest": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "intern-s1": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "intern-s1-mini": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "intern-s1-pro": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "intern-s2-preview": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "internvl-latest": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "internvl3.5-241b-a28b": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "internvl3.5-latest": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "kilo-auto/free": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "kimi-k2-thinking": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "kimi-k2.6": {
        "code": 0.59,
        "cost_efficiency": None,
        "quality": 0.6253,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "kimi-k2.7-code": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "labs-leanstral-1-5": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "labs-leanstral-1-5-1": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "leanstral": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "mimo-v2.5": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "mimo-v2.5-free": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "minimax-m2.7": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "minimax-m3": {
        "code": None,
        "cost_efficiency": None,
        "quality": 0.6641,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "minimax-m3:cloud": {
        "code": None,
        "cost_efficiency": None,
        "quality": 0.6641,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "minimaxai/minimax-m2.7": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "minimaxai/minimax-m3": {
        "code": None,
        "cost_efficiency": None,
        "quality": 0.6641,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "mistralai/Leanstral-1.5-119B-A6B": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "moonshotai/Kimi-K2-Instruct": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "moonshotai/Kimi-K2-Thinking": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "moonshotai/Kimi-K2.5": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "moonshotai/Kimi-K2.6": {
        "code": 0.59,
        "cost_efficiency": None,
        "quality": 0.6253,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "moonshotai/Kimi-K2.7-Code": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "moonshotai/kimi-k2-thinking": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "moonshotai/kimi-k2.6": {
        "code": 0.59,
        "cost_efficiency": None,
        "quality": 0.6253,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "nemotron-3-nano-omni-30b-reasoning": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "nemotron-3-nano:4b": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "nemotron-3-super": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "nemotron-3-ultra": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "nemotron-3-ultra-free": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "north-mini-code-free": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "nvidia/Nemotron-120B-A12B": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "nvidia/devstral-2-123b": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "nvidia/llama-3.1-nemotron-ultra-253b-v1": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "nvidia/nemotron-3-super-120b-a12b": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "nvidia/nemotron-3-super-120b-a12b:free": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "nvidia/nemotron-3-ultra-550b-a55b": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "openai/gpt-oss-120b": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "poolside/laguna-m.1:free": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "qwen/qwen3-next-80b-a3b-instruct": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "qwen/qwen3.5-122b-a10b": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "qwen/qwen3.5-397b-a17b": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "qwen2.5-coder:7b": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "qwen3-coder:480b": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "qwen3-next-80b": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "qwen3.5-397b": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "qwen3.6-plus-free": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "step-3.7-flash": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "stepfun-ai/step-3.5-flash": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "stepfun-ai/step-3.7-flash": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "stepfun/step-3.7-flash": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "stepfun/step-3.7-flash:free": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "vibethinker-3b": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "z-ai/glm-5.1": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "z-ai/glm-5.2": {
        "code": 0.684,
        "cost_efficiency": None,
        "quality": 0.7161,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "zai-org/GLM-4.5": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "zai-org/GLM-4.7": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "zai-org/GLM-5": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "zai-org/GLM-5.1": {
        "code": None,
        "cost_efficiency": None,
        "quality": None,
        "reasoning": None,
        "speed": None,
        "swe": None
    },
    "zai-org/GLM-5.2": {
        "code": 0.684,
        "cost_efficiency": None,
        "quality": 0.7161,
        "reasoning": None,
        "speed": None,
        "swe": None
    }
}

SCORES_PROVENANCE: dict = {
    "LongCat-2.0": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 93
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "MiniMaxAI/MiniMax-M2.1": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 80
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "MiniMaxAI/MiniMax-M2.5": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 84
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "MiniMaxAI/MiniMax-M3": {
        "as_of": "2026-07-08T00:00:00+00:00",
        "components": {
            "arena_score": 0.6641
        },
        "confidence": "low",
        "evidence_kind": "fixture",
        "policy_prior": {
            "registry_tier": 90
        },
        "provenance": "benchmark_snapshot",
        "sources": [
            "aa_intelligence_index",
            "aa_speed",
            "lmarena_elo"
        ],
        "weights": {}
    },
    "Qwen/Qwen3-235B-A22B": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 85
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "Qwen/Qwen3-32B": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 72
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "deepseek-ai/DeepSeek-V4-Flash": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 92
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "deepseek-ai/DeepSeek-V4-Pro": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 95
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "deepseek-ai/deepseek-v4-flash": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 92
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "deepseek-ai/deepseek-v4-pro": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 95
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "deepseek-v4-flash": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 92
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "deepseek-v4-flash-free": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 92
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "functiongemma:latest": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 30
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "glm-4.7": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 82
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "intern-latest": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 80
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "intern-s1": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 75
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "intern-s1-mini": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 70
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "intern-s1-pro": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 82
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "intern-s2-preview": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 85
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "internvl-latest": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 72
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "internvl3.5-241b-a28b": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 78
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "internvl3.5-latest": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 70
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "kilo-auto/free": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 60
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "labs-leanstral-1-5-1": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": None
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "mimo-v2.5-free": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 82
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "minimax-m2.7": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 60
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "minimax-m3:cloud": {
        "as_of": "2026-07-08T00:00:00+00:00",
        "components": {
            "arena_score": 0.6641
        },
        "confidence": "low",
        "evidence_kind": "fixture",
        "policy_prior": {
            "registry_tier": 90
        },
        "provenance": "benchmark_snapshot",
        "sources": [
            "aa_intelligence_index",
            "aa_speed",
            "lmarena_elo"
        ],
        "weights": {}
    },
    "minimaxai/minimax-m2.7": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 82
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "minimaxai/minimax-m3": {
        "as_of": "2026-07-08T00:00:00+00:00",
        "components": {
            "arena_score": 0.6641
        },
        "confidence": "low",
        "evidence_kind": "fixture",
        "policy_prior": {
            "registry_tier": 90
        },
        "provenance": "benchmark_snapshot",
        "sources": [
            "aa_intelligence_index",
            "aa_speed",
            "lmarena_elo"
        ],
        "weights": {}
    },
    "moonshotai/Kimi-K2-Instruct": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 80
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "moonshotai/Kimi-K2-Thinking": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 88
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "moonshotai/Kimi-K2.5": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 86
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "moonshotai/Kimi-K2.6": {
        "as_of": "2026-07-08T00:00:00+00:00",
        "components": {
            "arena_score": 0.6253,
            "code_score": 0.59
        },
        "confidence": "low",
        "evidence_kind": "fixture",
        "policy_prior": {
            "registry_tier": 90
        },
        "provenance": "benchmark_snapshot",
        "sources": [
            "aa_coding",
            "aa_intelligence_index",
            "aa_price",
            "aa_speed",
            "lmarena_code_elo",
            "lmarena_elo"
        ],
        "weights": {}
    },
    "moonshotai/Kimi-K2.7-Code": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 94
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "moonshotai/kimi-k2-thinking": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 88
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "moonshotai/kimi-k2.6": {
        "as_of": "2026-07-08T00:00:00+00:00",
        "components": {
            "arena_score": 0.6253,
            "code_score": 0.59
        },
        "confidence": "low",
        "evidence_kind": "fixture",
        "policy_prior": {
            "registry_tier": 90
        },
        "provenance": "benchmark_snapshot",
        "sources": [
            "aa_coding",
            "aa_intelligence_index",
            "aa_price",
            "aa_speed",
            "lmarena_code_elo",
            "lmarena_elo"
        ],
        "weights": {}
    },
    "nemotron-3-nano:4b": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 45
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "nemotron-3-ultra-free": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 88
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "north-mini-code-free": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 70
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 88
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "nvidia/Nemotron-120B-A12B": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 75
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "nvidia/devstral-2-123b": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 82
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "nvidia/llama-3.1-nemotron-ultra-253b-v1": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 0
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 85
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "nvidia/nemotron-3-super-120b-a12b": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 80
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "nvidia/nemotron-3-super-120b-a12b:free": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 80
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "nvidia/nemotron-3-ultra-550b-a55b": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 88
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "openai/gpt-oss-120b": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 78
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "poolside/laguna-m.1:free": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 70
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "qwen/qwen3-next-80b-a3b-instruct": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 84
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "qwen/qwen3.5-122b-a10b": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 80
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "qwen/qwen3.5-397b-a17b": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 86
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "qwen2.5-coder:7b": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 48
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "qwen3-coder:480b": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 86
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "qwen3.6-plus-free": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 84
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "stepfun-ai/step-3.5-flash": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 76
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "stepfun-ai/step-3.7-flash": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 84
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "stepfun/step-3.7-flash:free": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 84
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "vibethinker-3b": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 45
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "z-ai/glm-5.1": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 91
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "z-ai/glm-5.2": {
        "as_of": "2026-07-08T00:00:00+00:00",
        "components": {
            "arena_score": 0.7161,
            "code_score": 0.684
        },
        "confidence": "low",
        "evidence_kind": "fixture",
        "policy_prior": {
            "registry_tier": 96
        },
        "provenance": "benchmark_snapshot",
        "sources": [
            "aa_coding",
            "aa_intelligence_index",
            "aa_price",
            "aa_speed",
            "lmarena_code_elo",
            "lmarena_elo"
        ],
        "weights": {}
    },
    "zai-org/GLM-4.5": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 78
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "zai-org/GLM-4.7": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 82
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "zai-org/GLM-5": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 89
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "zai-org/GLM-5.1": {
        "as_of": None,
        "components": {},
        "confidence": "none",
        "evidence_kind": "none",
        "policy_prior": {
            "registry_tier": 91
        },
        "provenance": "unscored",
        "sources": [],
        "weights": {}
    },
    "zai-org/GLM-5.2": {
        "as_of": "2026-07-08T00:00:00+00:00",
        "components": {
            "arena_score": 0.7161,
            "code_score": 0.684
        },
        "confidence": "low",
        "evidence_kind": "fixture",
        "policy_prior": {
            "registry_tier": 95
        },
        "provenance": "benchmark_snapshot",
        "sources": [
            "aa_coding",
            "aa_intelligence_index",
            "aa_price",
            "aa_speed",
            "lmarena_code_elo",
            "lmarena_elo"
        ],
        "weights": {}
    }
}
