import os
import json
from pathlib import Path

transcript_path = Path("C:/Users/speci.000/.gemini/antigravity/brain/ccbebc95-504e-4833-a31a-25e97e24dacd/.system_generated/logs/transcript.jsonl")
output_dir = Path("c:/Users/speci.000/Documents/NEXUS/docs/wiki/briefs")

targets = {
    "NODE-WF-ASMRTEMPLLM": "ASMRtempLLM_brief.md",
    "NODE-WF-DARWINFLOW": "DARWINflow_brief.md",
    "NODE-WF-LLMDEVHALLICREASONS": "LLMdevHallicReasons_brief.md",
    "NODE-WF-SCIFLOW": "SCIflow_brief.md",
    "NODE-WF-RECURRING_LLM_MAS": "recurring-LLM_MAS_brief.md"
}

found = {}

print("Scanning transcript.jsonl...")
with open(transcript_path, "r", encoding="utf-8", errors="ignore") as f:
    for line_num, line in enumerate(f, 1):
        for target_id, target_file in targets.items():
            if target_id in line:
                # Try to parse line as JSON
                try:
                    data = json.loads(line)
                    # Search in different places of the step
                    # E.g. in tool_calls arguments, tool responses, model output, etc.
                    str_data = json.dumps(data)
                    # Let's extract blocks of markdown that contain the target_id
                    # and check if they look like a full brief.
                    # A brief starts with frontmatter "---" and has the target_id, and ends with "---" and the analysis content.
                    # Let's search for the markdown file content pattern.
                    import re
                    matches = re.findall(r'---[\r\n]+id:\s*' + target_id + r'[\s\S]*?---[\s\S]*?Generated by Gemma-4-12b-it', str_data)
                    for match in matches:
                        # Clean up escape characters
                        clean_match = match.replace("\\n", "\n").replace("\\r", "\r").replace('\\"', '"').replace("\\t", "\t")
                        if "Failed Technical Brief" not in clean_match and "Failed Technical Analysis" not in clean_match:
                            if target_id not in found or len(clean_match) > len(found[target_id]):
                                found[target_id] = clean_match
                                print(f"Found candidate for {target_id} in line {line_num} (len: {len(clean_match)})")
                except Exception as e:
                    # Fallback to simple regex if JSON parsing fails
                    pass

print("\nResults:")
for target_id, target_file in targets.items():
    if target_id in found:
        out_path = output_dir / target_file
        # Write to file
        content = found[target_id]
        # Ensure it has trailing newline and matches markdown format
        out_path.write_text(content, encoding="utf-8")
        print(f"[SUCCESS] Restored {target_file} (len: {len(content)})")
    else:
        print(f"[FAILED] Could not find brief for {target_id} in logs")
