import os
from pathlib import Path
import json

steps_dir = Path("C:/Users/speci.000/.gemini/antigravity/brain/ccbebc95-504e-4833-a31a-25e97e24dacd/.system_generated/steps")
image_basenames = ["ASMRtempLLM", "DARWINflow", "LLMdevHallicReasons", "SCIflow", "recurring-LLM_MAS"]

print("Searching steps files for raw IDs...")

for name in image_basenames:
    target_id = f"NODE-WF-{name.upper().replace('-', '_')}"
    print(f"\nSearching for {target_id}...")
    
    # We want to find the step content.md file that contains this ID
    found_files = []
    for f in steps_dir.rglob("content.md"):
        try:
            content = f.read_text(encoding="utf-8", errors="ignore")
            if target_id in content:
                print(f"  Found in {f.relative_to(steps_dir)} (len={len(content)})")
                found_files.append((f, len(content)))
        except Exception as e:
            pass
            
    if found_files:
        # Sort by size to get the one with the most content (likely the actual write_to_file step)
        found_files.sort(key=lambda x: x[1], reverse=True)
        best_file, size = found_files[0]
        print(f"  Best match: {best_file.relative_to(steps_dir)}")
        
        # Let's read the content and extract the brief
        content = best_file.read_text(encoding="utf-8", errors="ignore")
        # The brief content starts with `---` and ends with `Generated by Gemma-4-12b-it...`
        # But it might be escaped (e.g. \n or \\n)
        # Let's search for the pattern
        # Since it's escaped, let's look for a block that has `---` (or `---` with escapes) and the target_id
        # Let's just find the indexes of `---` around the target_id
        # Actually, let's search for "id: NODE-WF-..." and search backwards for "---" and forwards for the end of the brief.
        # Let's write a robust extraction logic:
        # We can unescape the entire content first!
        # If we unescape it, then it becomes normal markdown and we can extract it easily.
        unescaped = content.replace("\\n", "\n").replace("\\r", "\r").replace('\\"', '"').replace("\\t", "\t")
        
        # Now search for the brief in the unescaped text
        # It starts with "---" and has the target_id, then has "---", then the content, ending with "Generated by Gemma-4..."
        # Let's use a regex on the unescaped text
        match = re.search(r'---[\r\n]+id:\s*' + target_id + r'[\s\S]*?Generated by Gemma-4-12b-it.*', unescaped)
        if match:
            brief_text = match.group(0)
            # Sometimes there might be trailing quotes or junk, let's clean it up
            # Let's find the end of the brief: the date/time after Gemma-4-12b-it
            end_match = re.search(r'Generated by Gemma-4-12b-it on \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}', brief_text)
            if end_match:
                brief_text = brief_text[:end_match.end()] + "\n*\n"
            
            # Let's save it!
            out_path = Path(f"c:/Users/speci.000/Documents/NEXUS/docs/wiki/briefs/{name}_brief.md")
            out_path.write_text(brief_text, encoding="utf-8")
            print(f"  [SUCCESS] Extracted and saved to briefs/{name}_brief.md (len={len(brief_text)})")
        else:
            print("  [ERROR] Could not extract brief from unescaped content using regex")
