import os
from pathlib import Path
import re

tasks_dir = Path("C:/Users/speci.000/.gemini/antigravity/brain/ccbebc95-504e-4833-a31a-25e97e24dacd/.system_generated/tasks")
output_dir = Path("c:/Users/speci.000/Documents/NEXUS/docs/wiki/briefs")

image_basenames = [
    "ASMRtempLLM",
    "DARWINflow",
    "LLMdevHallicReasons",
    "SCIflow",
    "recurring-LLM_MAS"
]

print("Scanning task log files...")
found = {}

for f in tasks_dir.glob("task-*.log"):
    # Read first 1MB or search if it's not too huge, or read in chunks
    if f.stat().st_size > 0:
        try:
            content = f.read_text(encoding="utf-8", errors="ignore")
            for name in image_basenames:
                target_id = f"NODE-WF-{name.upper().replace('-', '_')}"
                if target_id in content and "Technical Analysis" in content:
                    print(f"  Found {target_id} in {f.name} (len={len(content)})")
                    # Try to extract the brief
                    # Since it is a terminal command log or script output, it might contain the brief content
                    # Let's search for the pattern
                    # Unescape just in case
                    unescaped = content.replace("\\n", "\n").replace("\\r", "\r").replace('\\"', '"').replace("\\t", "\t")
                    match = re.search(r'---[\r\n]+id:\s*' + target_id + r'[\s\S]*?Generated by Gemma-4-12b-it.*', unescaped)
                    if match:
                        brief_text = match.group(0)
                        end_match = re.search(r'Generated by Gemma-4-12b-it on \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}', brief_text)
                        if end_match:
                            brief_text = brief_text[:end_match.end()] + "\n"
                        
                        if "Failed Technical Analysis" not in brief_text and "FAILED" not in brief_text:
                            if name not in found or len(brief_text) > len(found[name]):
                                found[name] = brief_text
                                print(f"    -> Extracted candidate of length {len(brief_text)}")
        except Exception as e:
            print(f"Error reading {f.name}: {e}")

print("\nRestoration Results:")
for name in image_basenames:
    if name in found:
        # Calculate/retrieve SHA256 of the image
        import hashlib
        img_path = Path(f"C:/Users/speci.000/Downloads/Workflows/{name}.png")
        if not img_path.exists():
            img_path = Path(f"C:/Users/speci.000/Downloads/Workflows/{name}.jpg")
        
        if img_path.exists():
            sha = hashlib.sha256(img_path.read_bytes()).hexdigest()
        else:
            sha = "ea0d36143eed841d1a6bd510b785cede2fb244051e38192302abd78b8d9b89bd"
            
        brief_content = found[name]
        
        # Ensure correct origin_sha256 in frontmatter
        if 'origin_sha256: ""' in brief_content:
            brief_content = brief_content.replace('origin_sha256: ""', f'origin_sha256: "{sha}"')
        elif 'origin_sha256' not in brief_content:
            parts = brief_content.split("---")
            if len(parts) >= 3:
                parts[1] += f'\norigin_sha256: "{sha}"\n'
                brief_content = "---".join(parts)
                
        out_file = output_dir / f"{name}_brief.md"
        out_file.write_text(brief_content, encoding="utf-8")
        print(f"[OK] Restored {name}_brief.md (len: {len(brief_content)})")
    else:
        print(f"[ERROR] Could not restore {name}_brief.md")
