"""GENERATED by scripts/gen_model_registry.py from config/models.registry.json — DO NOT EDIT (edit the registry, then regenerate)"""

GENERATED_DOMAIN_MAPPING: dict = {
    "code": {
        "primary": [
            {
                "model": "zai-org/GLM-5.2",
                "provider": "baseten",
                "tier": 95,
                "latency_ms": 500,
                "cost_per_1m": 0.0,
                "status": "up"
            },
            {
                "model": "zai-org/GLM-5.2",
                "provider": "siliconflow",
                "tier": 95,
                "latency_ms": 500,
                "cost_per_1m": 0.0,
                "status": "up"
            },
            {
                "model": "moonshotai/Kimi-K2.7-Code",
                "provider": "baseten",
                "tier": 94,
                "latency_ms": 500,
                "cost_per_1m": 0.0,
                "status": "up"
            },
            {
                "model": "deepseek-ai/DeepSeek-V4-Flash",
                "provider": "siliconflow",
                "tier": 92,
                "latency_ms": 500,
                "cost_per_1m": 0.0,
                "status": "up"
            },
            {
                "model": "deepseek-ai/deepseek-v4-flash",
                "provider": "nvidia",
                "tier": 92,
                "latency_ms": 500,
                "cost_per_1m": 0.0,
                "status": "up"
            },
            {
                "model": "deepseek-v4-flash-free",
                "provider": "opencode",
                "tier": 92,
                "latency_ms": 500,
                "cost_per_1m": 0.0,
                "status": "up"
            }
        ],
        "fallback_chain": [
            "zai-org/GLM-5.2",
            "zai-org/GLM-5.2",
            "moonshotai/Kimi-K2.7-Code",
            "deepseek-ai/DeepSeek-V4-Flash"
        ]
    },
    "reasoning": {
        "primary": [
            {
                "model": "deepseek-ai/DeepSeek-V4-Pro",
                "provider": "baseten",
                "tier": 95,
                "latency_ms": 500,
                "cost_per_1m": 0.0,
                "status": "up"
            },
            {
                "model": "deepseek-ai/DeepSeek-V4-Pro",
                "provider": "siliconflow",
                "tier": 95,
                "latency_ms": 500,
                "cost_per_1m": 0.0,
                "status": "up"
            },
            {
                "model": "deepseek-ai/deepseek-v4-pro",
                "provider": "nvidia",
                "tier": 95,
                "latency_ms": 500,
                "cost_per_1m": 0.0,
                "status": "up"
            },
            {
                "model": "MiniMaxAI/MiniMax-M3",
                "provider": "siliconflow",
                "tier": 90,
                "latency_ms": 500,
                "cost_per_1m": 0.0,
                "status": "up"
            },
            {
                "model": "minimaxai/minimax-m3",
                "provider": "nvidia",
                "tier": 90,
                "latency_ms": 500,
                "cost_per_1m": 0.0,
                "status": "up"
            },
            {
                "model": "minimax-m3:cloud",
                "provider": "ollama-cloud",
                "tier": 90,
                "latency_ms": 500,
                "cost_per_1m": 0.0,
                "status": "up"
            }
        ],
        "fallback_chain": [
            "deepseek-ai/DeepSeek-V4-Pro",
            "deepseek-ai/DeepSeek-V4-Pro",
            "deepseek-ai/deepseek-v4-pro",
            "MiniMaxAI/MiniMax-M3"
        ]
    },
    "research": {
        "primary": [
            {
                "model": "zai-org/GLM-5.2",
                "provider": "baseten",
                "tier": 95,
                "latency_ms": 500,
                "cost_per_1m": 0.0,
                "status": "up"
            },
            {
                "model": "deepseek-ai/DeepSeek-V4-Pro",
                "provider": "baseten",
                "tier": 95,
                "latency_ms": 500,
                "cost_per_1m": 0.0,
                "status": "up"
            },
            {
                "model": "zai-org/GLM-5.2",
                "provider": "siliconflow",
                "tier": 95,
                "latency_ms": 500,
                "cost_per_1m": 0.0,
                "status": "up"
            },
            {
                "model": "deepseek-ai/DeepSeek-V4-Pro",
                "provider": "siliconflow",
                "tier": 95,
                "latency_ms": 500,
                "cost_per_1m": 0.0,
                "status": "up"
            },
            {
                "model": "deepseek-ai/deepseek-v4-pro",
                "provider": "nvidia",
                "tier": 95,
                "latency_ms": 500,
                "cost_per_1m": 0.0,
                "status": "up"
            },
            {
                "model": "moonshotai/Kimi-K2.7-Code",
                "provider": "baseten",
                "tier": 94,
                "latency_ms": 500,
                "cost_per_1m": 0.0,
                "status": "up"
            }
        ],
        "fallback_chain": [
            "zai-org/GLM-5.2",
            "deepseek-ai/DeepSeek-V4-Pro",
            "zai-org/GLM-5.2",
            "deepseek-ai/DeepSeek-V4-Pro"
        ]
    },
    "fast": {
        "primary": [
            {
                "model": "deepseek-ai/DeepSeek-V4-Flash",
                "provider": "siliconflow",
                "tier": 92,
                "latency_ms": 500,
                "cost_per_1m": 0.0,
                "status": "up"
            },
            {
                "model": "deepseek-ai/deepseek-v4-flash",
                "provider": "nvidia",
                "tier": 92,
                "latency_ms": 500,
                "cost_per_1m": 0.0,
                "status": "up"
            },
            {
                "model": "deepseek-v4-flash-free",
                "provider": "opencode",
                "tier": 92,
                "latency_ms": 500,
                "cost_per_1m": 0.0,
                "status": "up"
            },
            {
                "model": "stepfun-ai/step-3.7-flash",
                "provider": "nvidia",
                "tier": 84,
                "latency_ms": 500,
                "cost_per_1m": 0.0,
                "status": "up"
            },
            {
                "model": "stepfun/step-3.7-flash:free",
                "provider": "kilocode",
                "tier": 84,
                "latency_ms": 500,
                "cost_per_1m": 0.0,
                "status": "up"
            },
            {
                "model": "stepfun-ai/step-3.5-flash",
                "provider": "nvidia",
                "tier": 76,
                "latency_ms": 500,
                "cost_per_1m": 0.0,
                "status": "up"
            }
        ],
        "fallback_chain": [
            "deepseek-ai/DeepSeek-V4-Flash",
            "deepseek-ai/deepseek-v4-flash",
            "deepseek-v4-flash-free",
            "stepfun-ai/step-3.7-flash"
        ]
    },
    "security": {
        "primary": [
            {
                "model": "intern-s2-preview",
                "provider": "internai",
                "tier": 85,
                "latency_ms": 500,
                "cost_per_1m": 0.0,
                "status": "up"
            }
        ],
        "fallback_chain": [
            "intern-s2-preview"
        ]
    },
    "general": {
        "primary": [
            {
                "model": "zai-org/GLM-5.2",
                "provider": "baseten",
                "tier": 95,
                "latency_ms": 500,
                "cost_per_1m": 0.0,
                "status": "up"
            },
            {
                "model": "deepseek-ai/DeepSeek-V4-Pro",
                "provider": "baseten",
                "tier": 95,
                "latency_ms": 500,
                "cost_per_1m": 0.0,
                "status": "up"
            },
            {
                "model": "zai-org/GLM-5.2",
                "provider": "siliconflow",
                "tier": 95,
                "latency_ms": 500,
                "cost_per_1m": 0.0,
                "status": "up"
            },
            {
                "model": "deepseek-ai/DeepSeek-V4-Pro",
                "provider": "siliconflow",
                "tier": 95,
                "latency_ms": 500,
                "cost_per_1m": 0.0,
                "status": "up"
            },
            {
                "model": "deepseek-ai/deepseek-v4-pro",
                "provider": "nvidia",
                "tier": 95,
                "latency_ms": 500,
                "cost_per_1m": 0.0,
                "status": "up"
            },
            {
                "model": "moonshotai/Kimi-K2.7-Code",
                "provider": "baseten",
                "tier": 94,
                "latency_ms": 500,
                "cost_per_1m": 0.0,
                "status": "up"
            }
        ],
        "fallback_chain": [
            "zai-org/GLM-5.2",
            "deepseek-ai/DeepSeek-V4-Pro",
            "zai-org/GLM-5.2",
            "deepseek-ai/DeepSeek-V4-Pro"
        ]
    }
}
