"""GENERATED by scripts/gen_model_registry.py from config/models.registry.json — DO NOT EDIT (edit the registry, then regenerate)"""

GENERATED_DOMAIN_MAPPING: dict = {
    "code": {
        "primary": [
            {
                "model": "z-ai/glm-5.2",
                "provider": "nvidia",
                "tier": 96,
                "latency_ms": 500,
                "cost_per_1m": 1.0,
                "status": "up"
            },
            {
                "model": "deepseek-ai/DeepSeek-V4-Flash",
                "provider": "siliconflow",
                "tier": 92,
                "latency_ms": 500,
                "cost_per_1m": 1.0,
                "status": "up"
            },
            {
                "model": "zai-org/GLM-5.1",
                "provider": "siliconflow",
                "tier": 91,
                "latency_ms": 500,
                "cost_per_1m": 1.0,
                "status": "up"
            },
            {
                "model": "qwen3-coder:480b",
                "provider": "ollama-cloud",
                "tier": 86,
                "latency_ms": 500,
                "cost_per_1m": 1.0,
                "status": "up"
            },
            {
                "model": "glm-4.7",
                "provider": "ollama-cloud",
                "tier": 82,
                "latency_ms": 500,
                "cost_per_1m": 1.0,
                "status": "up"
            },
            {
                "model": "north-mini-code-free",
                "provider": "opencode",
                "tier": 70,
                "latency_ms": 500,
                "cost_per_1m": 1.0,
                "status": "up"
            }
        ],
        "fallback_chain": [
            "z-ai/glm-5.2",
            "deepseek-ai/DeepSeek-V4-Flash",
            "zai-org/GLM-5.1",
            "qwen3-coder:480b"
        ]
    },
    "reasoning": {
        "primary": [
            {
                "model": "z-ai/glm-5.2",
                "provider": "nvidia",
                "tier": 96,
                "latency_ms": 500,
                "cost_per_1m": 1.0,
                "status": "up"
            },
            {
                "model": "deepseek-ai/DeepSeek-V4-Pro",
                "provider": "siliconflow",
                "tier": 95,
                "latency_ms": 500,
                "cost_per_1m": 1.0,
                "status": "up"
            },
            {
                "model": "MiniMaxAI/MiniMax-M3",
                "provider": "siliconflow",
                "tier": 90,
                "latency_ms": 500,
                "cost_per_1m": 1.0,
                "status": "up"
            },
            {
                "model": "moonshotai/Kimi-K2-Thinking",
                "provider": "siliconflow",
                "tier": 88,
                "latency_ms": 500,
                "cost_per_1m": 1.0,
                "status": "up"
            },
            {
                "model": "qwen/qwen3.5-397b-a17b",
                "provider": "nvidia",
                "tier": 86,
                "latency_ms": 500,
                "cost_per_1m": 1.0,
                "status": "up"
            },
            {
                "model": "Qwen/Qwen3-235B-A22B",
                "provider": "siliconflow",
                "tier": 85,
                "latency_ms": 500,
                "cost_per_1m": 1.0,
                "status": "up"
            }
        ],
        "fallback_chain": [
            "z-ai/glm-5.2",
            "deepseek-ai/DeepSeek-V4-Pro",
            "MiniMaxAI/MiniMax-M3",
            "moonshotai/Kimi-K2-Thinking"
        ]
    },
    "research": {
        "primary": [
            {
                "model": "z-ai/glm-5.2",
                "provider": "nvidia",
                "tier": 96,
                "latency_ms": 500,
                "cost_per_1m": 1.0,
                "status": "up"
            },
            {
                "model": "deepseek-ai/DeepSeek-V4-Pro",
                "provider": "siliconflow",
                "tier": 95,
                "latency_ms": 500,
                "cost_per_1m": 1.0,
                "status": "up"
            },
            {
                "model": "zai-org/GLM-5.1",
                "provider": "siliconflow",
                "tier": 91,
                "latency_ms": 500,
                "cost_per_1m": 1.0,
                "status": "up"
            },
            {
                "model": "MiniMaxAI/MiniMax-M3",
                "provider": "siliconflow",
                "tier": 90,
                "latency_ms": 500,
                "cost_per_1m": 1.0,
                "status": "up"
            },
            {
                "model": "moonshotai/Kimi-K2.6",
                "provider": "siliconflow",
                "tier": 90,
                "latency_ms": 500,
                "cost_per_1m": 1.0,
                "status": "up"
            },
            {
                "model": "zai-org/GLM-5",
                "provider": "siliconflow",
                "tier": 89,
                "latency_ms": 500,
                "cost_per_1m": 1.0,
                "status": "up"
            }
        ],
        "fallback_chain": [
            "z-ai/glm-5.2",
            "deepseek-ai/DeepSeek-V4-Pro",
            "zai-org/GLM-5.1",
            "MiniMaxAI/MiniMax-M3"
        ]
    },
    "fast": {
        "primary": [
            {
                "model": "nemotron-3-nano:4b",
                "provider": "ollama",
                "tier": 45,
                "latency_ms": 50,
                "cost_per_1m": 0.0,
                "status": "local"
            }
        ],
        "fallback_chain": [
            "nemotron-3-nano:4b"
        ]
    },
    "security": {
        "primary": [
            {
                "model": "intern-s2-preview",
                "provider": "internai",
                "tier": 85,
                "latency_ms": 500,
                "cost_per_1m": 1.0,
                "status": "up"
            }
        ],
        "fallback_chain": [
            "intern-s2-preview"
        ]
    },
    "general": {
        "primary": [
            {
                "model": "z-ai/glm-5.2",
                "provider": "nvidia",
                "tier": 96,
                "latency_ms": 500,
                "cost_per_1m": 1.0,
                "status": "up"
            },
            {
                "model": "deepseek-ai/DeepSeek-V4-Pro",
                "provider": "siliconflow",
                "tier": 95,
                "latency_ms": 500,
                "cost_per_1m": 1.0,
                "status": "up"
            },
            {
                "model": "zai-org/GLM-5.1",
                "provider": "siliconflow",
                "tier": 91,
                "latency_ms": 500,
                "cost_per_1m": 1.0,
                "status": "up"
            },
            {
                "model": "MiniMaxAI/MiniMax-M3",
                "provider": "siliconflow",
                "tier": 90,
                "latency_ms": 500,
                "cost_per_1m": 1.0,
                "status": "up"
            },
            {
                "model": "moonshotai/Kimi-K2.6",
                "provider": "siliconflow",
                "tier": 90,
                "latency_ms": 500,
                "cost_per_1m": 1.0,
                "status": "up"
            },
            {
                "model": "zai-org/GLM-5",
                "provider": "siliconflow",
                "tier": 89,
                "latency_ms": 500,
                "cost_per_1m": 1.0,
                "status": "up"
            }
        ],
        "fallback_chain": [
            "z-ai/glm-5.2",
            "deepseek-ai/DeepSeek-V4-Pro",
            "zai-org/GLM-5.1",
            "MiniMaxAI/MiniMax-M3"
        ]
    }
}
